### PR TITLE
1451037: Allow tomcat to read /etc/candlepin (0.9.49)

### PR DESCRIPTION
**Pull request by kahowell**

### CODE REVIEW

**Comment by mstead** [comment]
retest this please

**Comment by kahowell** [comment]
ce50422..1abfb01:
 - added /var/{cache,lib,log}/candlepin rules
 - use macros for permissions
 - add missing rule

**Comment by kahowell** [comment]
1abfb01..1740b7d: add restorecon calls for new rules

**Comment by kahowell** [comment]
1740b7d..04a873c: fix BZ# in git commit message

**Pull request merged**
