### PR TITLE
[4.0] 1949980: Fix SCA cert regeneration for consumers in environments (ENT-3784)

### PR DESCRIPTION
**Pull request by Ceiu**
- Fixed a duplicate key error that could occur when regenerating
  SCA certs for a consumer that already had an expired or outdated
  certificate that was part of an environment

### CODE REVIEW

**Comment by Ceiu** [comment]
We may want to hold off on merging this PR until we decide what we're doing with the caching change in master. If that ends up being better to backport, this fix should be omitted from 4.0.

**Comment by nikosmoum** [comment]
@Ceiu Would it be problematic if we merge this now, but also porting the per-consumer-caching on this branch later once ready?

**Review by nikosmoum — APPROVED** [review]

**Comment by Ceiu** [comment]
Yeah. We could also just leave this branch as-is and focus the efforts of the caching changes purely in 4.1. I'm fine with either.

**Comment by nikosmoum** [comment]
Leaving per-consumer-caching for 4.1 only sounds fine I think. Merging this then

**Pull request merged**
