### PR TITLE
1451031: Allow tomcat to read /etc/candlepin (2.0)

### PR DESCRIPTION
**Pull request by kahowell**

### CODE REVIEW

**Comment by mstead** [comment]
retest this please

**Comment by kahowell** [comment]
acb513f..ec54764:
 - added /var/{cache,lib,log}/candlepin rules
 - use macros for permissions
 - add missing rule

**Comment by kahowell** [comment]
ec54764..2c94740: add restorecon for new rules

**Comment by kahowell** [comment]
2c94740..09bf902: fix bz# in commit message

**Comment by cnsnyder** [comment]
Merging as it seems this change has nothing to do with the failed performance test.

(see https://trello.com/c/OElgNmQs/412-13-performace-tests-look-at-existing-test-failures-and-adjust-expected-success-criteria)

**Pull request merged**
