### PR TITLE
Backport of Batch Revoke to 9.23

### PR DESCRIPTION
**Pull request by nguyenfilip**
To make the unit tests pass, one of the commits ignores SSLCertTest.validCertificateShouldPassVerification test

After local run of rspec tests I can see the following failures

```
Failures:

  1) Authorization allows trusted consumer clients
     Failure/Error: trusted_cp.list_entitlements()
     RestClient::Unauthorized:
       401 Unauthorized
     # ./server/client/ruby/candlepin_api.rb:1078:in `get'
     # ./server/client/ruby/candlepin_api.rb:684:in `list_entitlements'
     # ./server/spec/authorization_spec.rb:45:in `block (2 levels) in <top (required)>'

  2) Authorization allows in trused users
     Failure/Error: trusted_user_cp.list_consumers :owner => owner1['key']
     RestClient::Unauthorized:
       401 Unauthorized
     # ./server/client/ruby/candlepin_api.rb:1078:in `get'
     # ./server/client/ruby/candlepin_api.rb:726:in `list_consumers'
     # ./server/spec/authorization_spec.rb:61:in `block (2 levels) in <top (required)>'

  3) OAuth lets a caller act as a user
     Failure/Error: res.code.should == '200'
       expected: "200"
            got: "401" (using ==)
     # ./server/spec/oauth_spec.rb:61:in `block (2 levels) in <top (required)>'

  4) OAuth trusts the provided username
     Failure/Error: res.code.should == '200'
       expected: "200"
            got: "401" (using ==)
     # ./server/spec/oauth_spec.rb:69:in `block (2 levels) in <top (required)>'

  5) OAuth lets a caller act as a consumer
     Failure/Error: res.code.should == '200'
       expected: "200"
            got: "401" (using ==)
     # ./server/spec/oauth_spec.rb:76:in `block (2 levels) in <top (required)>'

  6) OAuth falls back to trusted system auth if no headers are set
     Failure/Error: res.code.should == '200'
       expected: "200"
            got: "401" (using ==)
     # ./server/spec/oauth_spec.rb:89:in `block (2 levels) in <top (required)>'

Finished in 22 minutes 15 seconds
510 examples, 6 failures

```

### CODE REVIEW

**Comment by mstead** [comment]
This back port seems ok to me. I'll let another dev review as well before merging.

**Comment by mstead** [comment]
I verified with @nguyenfilip that the jenkins spec tests are expected and appear to have been broken in the original release. He has discussed with @awood.

**Comment by vritant** [comment]
Im good with the change in #1111

**Comment by vritant** [comment]
@nguyenfilip , @mstead and I talked, in case you know how to build Candlepin, please feel free to merge #1111 into #1110 ( unless you have some issues with it ), and also feel free to self merge #1110 into master.

if like me you are not familiar with the build process, please take a look at #1111, there is probably no need for the self merge, and @mstead can merge #1110  tomorrow.

**Pull request merged**
