### PR TITLE
Awood/dependency fixup

### PR DESCRIPTION
**Pull request by awood**
Fix a dependency issue and fix some tests that were failing due to a cert with a too short key.

### CODE REVIEW

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by nikosmoum** [comment]
I know this has already been merged, but since I'm reading up on our build process, I thought we need to update the pom.xml files every time we change dependencies in the buildfile, or our builds will get messed up?

**Comment by Ceiu** [comment]
Yes and no, though probably more yes than no. While the pom.xml isn't updated, it gets automatically updated as part of our other systems (such as deploy and build). So it's not strictly necessary, but it should be done since it'll cause pom.xml to constantly look like it's been modified.

**Comment by awood** [comment]
Crap.  I forgot to check in the updated pom.  I will do that.

**Comment by awood** [comment]
See #2245

**Pull request merged**
