### PR TITLE
1469575: purge orphan pools via liquibase

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by mstead** [comment]
retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
performance ok

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
I will fix these conflicts

**Comment by mstead** [comment]
> I will fix these conflicts

Done

**Comment by mstead** [comment]
retest this please

**Pull request merged**
