### PR TITLE
1932662: Fixed candlepin test data for dev-sku (ENT-3600)

### PR DESCRIPTION
**Pull request by wolfdale**
Issue :
Incomplete test data for dev SKU product. Commit - https://github.com/candlepin/candlepin/pull/2918/commits/10eefcac2ca1c2aa3b9f306587cd7adfea74edc9 changed the working of dev pools which now consider provided products as well.

Changes : 
- Added provided product to ```dev-sku-product```
- Created another dev product with no provided product ```dev-sku-no-provided-product```

### CODE REVIEW

**Comment by Ceiu** [comment]
ack

This appears to work as one would expect in both hosted and standalone test data injection and population. Whether or not it addresses the issue with dev skus that QE is hitting will need to be verified after #2949 is merged.

**Comment by nikosmoum** [comment]
Now that #2949 is merged this can be tested

**Comment by wolfdale** [comment]
- [x] Verified the test data correction made in this PR (Added provided product (100000000000011) to ```dev-sku-product```)
```
$ subscription-manager attach --auto
Installed Product Current Status:
Product Name: Awesome OS for x86_64/i686/ia64/ppc/ppc64/s390x/s390 Bits
Status:       Subscribed
```

Bug describe another problem (below), which need discussion to understand the issue.
> The existing "dev-sku-product" in the TESTDATA is unknown to the product proxy which blocks our ability to test the change in CDK behavior for ENT-1686 before it lands on a stage/prod entitlement server.

**Comment by jsefler** [comment]
I suggest dropping the ", no content" suffix from the name for "dev-sku-product" because this product now has one provided product with content sets.

**Comment by wolfdale** [comment]
@jsefler Done. Thanks for the help.
PR passed all necessary test cases. Good to merge.

**Comment by Ceiu** [comment]
ack

**Pull request merged**
