### PR TITLE
[M] 1503299: bind with an empty string as POST body

### PR DESCRIPTION
**Pull request by vritant**
ConsumerResource.bind should NEVER be provided with a POST body. While technically that change would be backwards compatible,  there are older clients which erroneously provide an empty string  as a post body and hence result in a serialization error.
 ref: BZ: 1502807

### CODE REVIEW

**Comment by vritant** [comment]
[1502807 : 2.0 bind with empty string body in ConsumerResource](https://trello.com/c/XaETyLUC/597-1502807-20-bind-with-empty-string-body-in-consumerresource)

**Comment by vritant** [comment]
@candlepin-pull-request-bot test this please

**Comment by Ceiu** [comment]
I've removed the "ignore Jenkins failures" tag, as we have the means of re-running individual tests without re-running the entire suite (however clumsy it may be).

I've also restarted the test in question to see if it passes. If this is one that's still giving us problems, we should work to patch it sooner than later. I don't want to see us get back into a spot where we need to spend a week fixing Jenkins failures to get things passing reliably again.

**Comment by mstead** [comment]
> I don't want to see us get back into a spot where we need to spend a week fixing Jenkins failures to get things passing reliably again.

Couldn't agree more!

**Pull request merged**
