### PR TITLE
Gradle Initial PR

### PR DESCRIPTION
**Pull request by barnabycourt**
Create a baseline gradle build that is capable of running the standard unit tests & generating the war file.

### CODE REVIEW

**Comment by wottop** [comment]
Do you want to squash before merging?
ack, otherwise

**Comment by barnabycourt** [comment]
@wottop I squashed 2 of the commits, the rest provide segmenting of the work I'd like to keep

**Comment by barnabycourt** [comment]
test this please

**Comment by wottop** [comment]
ack

**Pull request merged**
