### PR TITLE
1498216: Use the environment name in the certificate

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Comment by wottop** [comment]
[Bug 1498215: When using Organizational/Environment Level Content Access, systems cannot install packages](https://trello.com/c/2RM75T8D/589-bug-1498215-when-using-organizational-environment-level-content-access-systems-cannot-install-packages)

**Comment by wottop** [comment]
retest this please

**Comment by mstead** [comment]
Are there any steps that we should follow to test this fix?

**Comment by wottop** [comment]
To test the DN entry:
Build CP as hosted

Change the content access mode on owner snowwhite:

curl -k -u admin:admin --request PUT --data '{"contentAccessMode":"org_environment"}' --header 'accept:application/json' --header 'content-type: application/json' https://localhost:8443/candlepin/owners/snowwhite

Add an environment

curl -k -u admin:admin --request POST --data '{"id":"CA-env-id","name":"CA-env-name"}' --header 'accept:application/json' --header 'content-type: application/json' https://localhost:8443/candlepin/owners/snowwhite/environments

Register a client to CP on owner snowwhite

On the client use cat-cert to see the Subject section

Subject:
	CN: 2978a213-5f6c-4637-a145-b9c84d7ca7d7
	O: snowwhite
	OU: CA-env-name

**Pull request merged**
