### PR TITLE
2036746: Fix Illegal embedded sign character

### PR DESCRIPTION
**Pull request by Januson**
- Update testdata to generate content id without dash
- Strip non-numeric characters from content id before we use it for oid

### CODE REVIEW

**Comment by barnabycourt** [comment]
If the test was embedding an illegal sign character, but that character was being accepted by the API, shouldn't the validation be updated for the create ProductContent to disallow creation with the invalid data?

**Comment by Januson** [comment]
@barnabycourt Sure. If we are ok with changing the API we can start rejecting them at creation. I updated only the OID creation as it keeps the API behavior.

**Comment by Ceiu** [comment]
Given that this is a limitation of v1 certs, and we've never imposed this limitation before, it probably doesn't make sense to do so now. Are there other factors here that might cause problems if there are non-numeric characters in a content ID?

**Comment by nikosmoum** [comment]
I agree with Chris. If non-numeric characters in ids already work with v3 certs, and there are users out there that use them, we'd break them, so I don't think we want to validate at the API. The current change seems better since it only happens at the v1 cert generation path; either that, or throwing a human readable exception at this point that says 'ids with non-numeric characters are not supported for clients with v1 certificates'

**Comment by Ceiu** [comment]
Do we have a means of limiting a CP deployment to only v1 certs? If not, it probably doesn't make sense to add the limit on the API. 

My only concern with this, I guess, is the question of whether or not the content ID being slightly different in the cert OID has any impact with a content lookup or fetch op from a v1-restricted client. Are we at risk of any ID desync that we'd need to address?

**Comment by nikosmoum** [comment]
@Ceiu I think in order to avoid such issues, it might be cleaner to just throw a descriptive error during the v1 cert generation (instead of the current error). Especially since no customer has actually complained about this (it was find by us).

**Review by nikosmoum — APPROVED** [review]
ACK from me

**Pull request merged**
