### PR TITLE
Added the new org.candlepin.dto package

### PR DESCRIPTION
**Pull request by Ceiu**
- Added the new org.candlepin.dto package with new DTOs, translators
  and DTO factories
- Added the standard DTOFactory object, which acts as a registry for
  EntityTranslator instances
- Added the EntityTranslator interface, which defines/describes the methods
  for converting a model entity to a DTO
- Added DTOs for Owner, UpstreamConsumer, ConsumerType, Certificate
  and CertificateSerial, and their respective translators
- Added the ModelEntity and TimestampedModelEntity interfaces which
  represent database model entities
- AbstractHibernateObject now implements TimestampedModelEntity
- OwnerProduct and OwnerContent now implement ModelEntity
- Added the APIDTOFactory and the APIv1DTOFactory, both registered in
  the CandlepinModule for injection into the endpoint handlers
- Implemented the new DTOs in their respective resources
- Removed several now-extraneous helper methods from Owner which
  provided targeted output for serialization

### CODE REVIEW

**Comment by Ceiu** [comment]
Note for reviewers:
In a future commit, I plan to rename DTOFactory to ModelTransformer (name pending), EntityTranslator to ModelTranslator, and lift the generic restriction from the DTOFactory so translators can be written in both directions.

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by mstead** [comment]
retest this please

**Comment by Ceiu** [comment]
retest this please

**Comment by Ceiu** [comment]
Running the failing tests locally passes. Gonna need to look into this a bit more to understand why the failures are occurring in the Jenkins environment.

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
@Ceiu I'm going to kick the tests off again since I believe there's some work that has been done on the jenkins environment. If they don't run successfully, I'm going to run them locally myself, and merge if they are ok for me.

**Pull request merged**
