### PR TITLE
returns response code 202 on successful subscription activation

### PR DESCRIPTION
**Pull request by cnsnyder**

### CODE REVIEW

**Comment by awood** [comment]
candlepin-pull-request-bot, add to whitelist

**Comment by awood** [comment]
@cnsnyder Looks good, but let's squash all these commits together.  I can give you a tutorial, but the basic concepts are explained [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages).

**Comment by cnsnyder** [comment]
@awood Commits squashed! Thanks for your help! :)

**Comment by Ceiu** [comment]
retest this please

**Comment by cnsnyder** [comment]
@Ceiu The checks seem to have passed on jenkins, do you need / want me to retest again locally?

**Comment by Ceiu** [comment]
@cnsnyder That was just a command to get jenkins to restart the tests, you can disregard it.

**Pull request merged**
