### PR TITLE
[2.1] 1525204: Lock update consumer avoid to constraint violation with hypervi…

### PR DESCRIPTION
**Pull request by wottop**
…sor checkin

To test, run the new spec test against 2.1 HOTFIX. You will be able to see the consumerUpdate failure.
The added locking will keep the violation from occurring.

### CODE REVIEW

**Comment by kahowell** [comment]
Looks like checkstyle should pass once #1855 lands.

**Comment by wottop** [comment]
[[8] BZ: 1502193 - periodic mysql exceptions when updating consumers in production](https://trello.com/c/kr5KOoAR/600-8-bz-1502193-periodic-mysql-exceptions-when-updating-consumers-in-production)

**Comment by wottop** [comment]
retest this please

**Comment by barnabycourt** [comment]
Adding in progress flag until we have appropriate approvals for the release

**Comment by barnabycourt** [comment]
This needs to  be updated to include a fix similar to the one in https://github.com/candlepin/candlepin/compare/candlepin-2.2-HOTFIX...crog/2.2/1531628 to change the fetchmode of the type attribute or other shared sub-objects of the consumer that are not being changed so a pessimistic lock is not held across multiple orgs or consumers inadvertently

**Comment by Ceiu** [comment]
We'll revisit this once we have time to evaluate the locking mechanism properly, and/or can use the DTOs to avoid pulling the consumer type with every consumer.

**Pull request closed without merging**
