### PR TITLE
[M] 1563003: Removed extraneous validation on default service level

### PR DESCRIPTION
**Pull request by Ceiu**
- Default service level is no longer validated during owner creation
  or update

### CODE REVIEW

**Comment by Ceiu** [comment]
Seems reverting this change (re)introduces a bit of an inconsistency. Our tests indicate that we've been expecting this to fail on update, but either don't expect it or weren't testing it during creation. I want to have time to look into this more before we merge this and potentially make this situation worse.

**Comment by vritant** [comment]
@Ceiu @cnsnyder adding myself as additional reviewer.
This fixes bug: 1565066 as well imo.

**Comment by Ceiu** [comment]
Closing this PR as the "fix" here is not to change behavior, but to clean up the error message and add a new error for attempting to provide a default service level on owner creation.

A new PR will be posted with these fixes shortly.

**Comment by Ceiu** [comment]
New PR: #1965

**Pull request closed without merging**
