### PR TITLE
Disable creation of share consumers in 2.1

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by mstead** [comment]
@vritant Please add some context to the commit message as to why we are doing this. i.e Feature is not yet ready...

**Comment by mstead** [comment]
retest this please

**Comment by awood** [comment]
bot, retest this please

**Comment by awood** [comment]
Some unit test failures here:

```
 Expected: (an instance of org.candlepin.common.exceptions.BadRequestException and exception with message a string containing "must specify a recipient org")
    [junit]      but: an instance of org.candlepin.common.exceptions.BadRequestException <org.candlepin.common.exceptions.ForbiddenException: Multi-org sharing is currently not supported> is a org.candlepin.common.exceptions.ForbiddenException
```

I imagine you can just `@Skip` (or whatever JUnit uses to skip tests) those tests.

**Comment by vritant** [comment]
@awood  fixed

**Comment by barnabycourt** [comment]
retest this please

**Comment by barnabycourt** [comment]
@vritant still a qpid error, not sure if it is related.

**Comment by vritant** [comment]
@candlepin-pull-request-bot test this please

**Pull request merged**
