### PR TITLE
The per-org products migration now fails on unresolvable products (2.0)

### PR DESCRIPTION
**Pull request by Ceiu**
- The per-org products migration task will now fail if it detects
  any unresolvable products, rather than continuing with a warning.
  This should eliminate the situation where pools ended up with
  null or absent product references post-migration.

### CODE REVIEW

**Comment by Ceiu** [comment]
**Testing**
- Deploy a 0.9.x CP with test data
- Modify any of the following such that they're either null, empty strings or invalid/non-existing product IDs:
    - cp_pool.productid
    - cp_pool_product.product_id
    - cp_subscription.product_id
    - cp_subscription_product.product_id

- Modify any of the following such that they reference invalid/non-existing product IDs:
    - cp_pool.derivedproductid
    - cp_subscription.derived_product_id

- Check out this branch and perform a normal deployment with -v, preferably piped to a file for safety:
```./bin/deploy -v | tee deploy.txt```

- Verify that with nulls or invalid product IDs as specified above, the migration fails with a DatabaseException specifying that one or more orgs failed data validation.
- Verify that the log contains an error message for each of the invalid or null products created in the test data

**Comment by mstead** [comment]
retest this please

**Comment by Ceiu** [comment]
[Make per-org products migration task fail if it detects unresolvable product references](https://trello.com/c/BdDME9so/394-make-per-org-products-migration-task-fail-if-it-detects-unresolvable-product-references)

**Comment by Ceiu** [comment]
retest this please

**Comment by Ceiu** [comment]
retest this please

**Pull request merged**
