### PR TITLE
Consolidate request and response logging into one log statement.

### PR DESCRIPTION
**Pull request by awood**
Previously the components of a request and/or response were spread
across multiple log statements.  One at INFO level would log the verb
and requested URL (or the response code) and one at DEBUG level would
log the headers and body.  Splitting what should logically be a single
unit across multiple statements made reading the logs harder than
necessary.

This patch consolidates an entire request and/or response into a single
statement.  If the logger is set to INFO, it writes a short statement
with the verb and URL combination (or response code).  If the logger is
set to DEBUG, it skips the aforementioned INFO statement and writes a
longer statement with the headers and body.

From this:

```
2015-02-04 11:50:09,849 [req=840fd586-b40b-4ef6-b3e6-0587c17d4e07, org=] INFO  org.candlepin.common.filter.LoggingFilter - Request: verb=GET, uri=/candlepin/pools?owner=8a8d01d34b556ac3014b557fab7f42e5&
2015-02-04 11:50:09,850 [req=840fd586-b40b-4ef6-b3e6-0587c17d4e07, org=] DEBUG org.candlepin.common.filter.LoggingFilter - 
====Headers====
  accept: application/json
  accept-encoding: gzip, deflate
  accept-language: 
  user-agent: Ruby
  authorization: Basic YWRtaW46YWRtaW4=
  host: localhost:8443
====End Headers====
====Request Body====
```

to this

```
2015-03-24 14:51:33,229 [req=3e2ddfba-ae3f-46ed-8d8a-82b60e007521, org=] DEBUG org.candlepin.common.filter.LoggingFilter - 
Request: POST /candlepin/jobs/refresh_pools_075a0025-0685-4105-bab2-cb59d85c60dcaccept: application/json
accept-encoding: gzip, deflate
accept-language: 
content-type: application/json
user-agent: Ruby
authorization: Basic YWRtaW46YWRtaW4=
host: localhost:8443
content-length: 0
---
```

### CODE REVIEW

**Comment by awood** [comment]
It might be nice to indent the request and response statement to make it stand out more.  Does anyone else have an opinion about that idea?

**Comment by dgoodwin** [comment]
Per call my main concern sounds like it's not an issue. 

If we did have owner debug on for an account, it would be useful for the first line of the statement to appear the same as it does in info level:


2015-03-24 14:51:33,229 [req=3e2ddfba-ae3f-46ed-8d8a-82b60e007521, org=] DEBUG org.candlepin.common.filter.LoggingFilter - Request: POST /candlepin/jobs/refresh_pools_075a0025-0685-4105-bab2-cb59d85c60dc

I'm not positive if that's just line wrapping in github now though, but if request + verb + URL is on the same line as the timestamp and request UUID, we're in much better shape for searching.

Might be an issue with "accept" missing a newline (see end of URL in new output)

**Comment by awood** [comment]
@dgoodwin Okay, Let me put the verb + URL on the top line.  I like them on the right so they line up with everything else, but yeah it would be unfriendly to log reading tools.  Maybe I can figure out a compromise.

**Comment by awood** [comment]
Just for laughs, I wrote a custom plugin to `ccze` to colorize the Candlepin log.  I'm not quite done, but the nice thing about it is we could use it to add a newline to keep the entire request on the left.

Here's a screenshot
ccze

And the code is 

```c
#include <ccze.h>
#include <stdlib.h>
#include <string.h>

static void ccze_candlepin_setup (void);
static void ccze_candlepin_shutdown (void);
static int ccze_candlepin_handle (const char *str, size_t length, char **rest);

static pcre *reg_candlepin_access, *reg_candlepin_other;
static pcre_extra *hints_candlepin_access, *hints_candlepin_other;

static ccze_color_t _ccze_candlepin_level (const char *level) {
  if (strstr (level, "DEBUG") || strstr (level, "INFO"))
    return CCZE_COLOR_DEBUG;
  if (strstr (level, "WARN"))
    return CCZE_COLOR_WARNING;
  if (strstr (level, "ERROR"))
    return CCZE_COLOR_ERROR;
  return CCZE_COLOR_UNKNOWN;
}

static char * ccze_candlepin_access_log_process (const char *str, int *offsets, int match) {
  char *date, *time, *mdc, *log_level, *class, *message;
  ccze_color_t lcol;

  pcre_get_substring(str, offsets, match, 1, (const char**)&date);
  pcre_get_substring(str, offsets, match, 2, (const char**)&time);
  pcre_get_substring(str, offsets, match, 3, (const char**)&mdc);
  pcre_get_substring(str, offsets, match, 4, (const char**)&log_level);
  pcre_get_substring(str, offsets, match, 5, (const char**)&class);
  pcre_get_substring(str, offsets, match, 6, (const char**)&message);

  ccze_addstr (CCZE_COLOR_DATE, date);
  ccze_space ();
  ccze_addstr (CCZE_COLOR_FIELD, time);
  ccze_space ();

  ccze_addstr (CCZE_COLOR_STATIC_BLUE, mdc);
  ccze_space();

  lcol = _ccze_candlepin_level(log_level);
  ccze_addstr (lcol, log_level);
  ccze_space ();

  ccze_addstr (CCZE_COLOR_SUBJECT, class);
  ccze_space ();

  ccze_addstr (CCZE_COLOR_DEFAULT, "-");
  ccze_space ();

  ccze_addstr (CCZE_COLOR_DEFAULT, message);
  ccze_newline ();

  free (date);
  free (time);
  free (mdc);
  free (log_level);
  free (class);
  free (message);

  return NULL;
}

static char * ccze_candlepin_other_log_process (const char *str, int *offsets, int match) {
  char *msg;

  pcre_get_substring (str, offsets, match, 1, (const char **)&msg);

  ccze_addstr (CCZE_COLOR_DEFAULT, msg);
  ccze_newline ();

  free (msg);

  return NULL;
}

static void ccze_candlepin_setup (void) {
  const char *error;
  int errptr;

  reg_candlepin_access = pcre_compile
    ("^(\\d{4}-\\d{2}-\\d{2})"
     "\\s(\\d{2}:\\d{2}:\\d{2},\\d{3})"
     "\\s(\\[.*?\\])"
     "\\s(\\w+)"
     "\\s(.+?)\\s-\\s"
     "(.*)$",
     0, &error, &errptr, NULL);
  hints_candlepin_access = pcre_study (reg_candlepin_access, 0, &error);

  reg_candlepin_other = pcre_compile
    ("^(.*)$",
     0, &error, &errptr, NULL);
  hints_candlepin_other = pcre_study (reg_candlepin_other, 0, &error);
}

static void ccze_candlepin_shutdown (void) {
  free (reg_candlepin_access);
  free (hints_candlepin_access);
  free (reg_candlepin_other);
  free (hints_candlepin_other);
}

static int ccze_candlepin_handle (const char *str, size_t length, char **rest) {
  int match, offsets[99];

  if ((match = pcre_exec (reg_candlepin_access, hints_candlepin_access,
			  str, length, 0, 0, offsets, 99)) >= 0)
    {
      *rest = ccze_candlepin_access_log_process (str, offsets, match);
      return 1;
    }
  if ((match = pcre_exec (reg_candlepin_other, hints_candlepin_other,
			  str, length, 0, 0, offsets, 99)) >= 0)
    {
      *rest = ccze_candlepin_other_log_process (str, offsets, match);
      return 1;
    }

  return 0;
}

CCZE_DEFINE_PLUGIN (candlepin, FULL, "Coloriser for candlepin log.");
```

Although I am currently building it against a source distribution of ccze with a hacked up Makefile.  If I figure out a decent build process, I will let everyone know.  Or I can of course just share the generated `.so` file which you just dump in `~/.ccze`.

I guess the really ambitious programmer would write Python bindings to the methods in `ccze.h` and then in the plugin just load a `.py` file that is using those bindings.  I don't know much about that though.  Maybe in version 2!

**Pull request merged**
