### PR TITLE
CANDLEPIN-536: Update JSON time serializer for ISO-8601

### PR DESCRIPTION
**Pull request by wottop**
Update JSON time serializer to follow more strict ISO-8601 derivatives
- When we specify the format as date-time for a given field, the OpenAPI spec
 expects it to be an RFC-3339 date-time, which while close to the basic
 ISO-8601 format, does not permit omitting the colon in the offset.
- This is handled in code with the DateTimeFormatter.ISO_OFFSET_DATE_TIME
 which claims to be ISO-8601 lenient, but still has a requirement of the
 colon in the zone offset.

Ensure Status output has proper UTC time
- Previously we relied on the value to come from a system set to
  UTC already. This will ensure it is in UTC regardless of the system
  setting.

### CODE REVIEW

**Comment by Ceiu** [comment]
While this patch fixes the immediate problem and corrects the output of the status endpoint, I'm not sure it fixes the underlying root cause of the parsing error. Do we know why non-UTC timestamps were causing problems? Are we confident that this won't occur when parsing any other timestamps we might return?

**Comment by wottop** [comment]
We seem to be at the mercy of a generated class in the client:
client/build/generated/src/main/java/org/candlepin/invoker/client/JSON.java
it only knows how to deal with dates ending with "+0000"

**Comment by Ceiu** [comment]
The comments in the generated code have the answer here:
When we specify the format as `date-time` for a given field, the OpenAPI spec expects it to be an RFC-3339 date-time, which while close to the basic ISO-8601 format, does not permit omitting the colon in the offset. Amusingly, this is handled in code with the `DateTimeFormatter.ISO_OFFSET_DATE_TIME` which claims to be ISO-8601 lenient, but still has a requirement of the colon in the zone offset (see: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/ZoneOffset.html#getId())

We can fix this in our code by adding the colon in the OffsetDateTimeSerializer and ensuring we're following the more strict ISO-8601 derivatives. Since we're still staying within spec by adding it, we shouldn't break any existing clients.

**Comment by Ceiu** [comment]
We should also add these details as a commit comment

**Review by Ceiu — CHANGES_REQUESTED** [review]
See previous comments for change request

**Review by Ceiu — CHANGES_REQUESTED** [review]
These look good, but the change to ensure the timeUTC field is always in UTC is still something we should do. So that should either be brought back in this PR, added as another commit on this PR, or another PR entirely.

Also the commit message should be formatted closer to our guidelines for that.

**Review by Ceiu — APPROVED** [review]

**Pull request merged**
