### PR TITLE
fix deletePools - delete derived pools

### PR DESCRIPTION
**Pull request by vritant**
unless its a data error, I think delete pools wrongfully assumes that **all** derived pools will be deleted when we delete master pools.

### CODE REVIEW

**Comment by vritant** [comment]
While I think this fix is good, there are some more pools not being deleted and I'd like to investigate more.

**Comment by vritant** [comment]
points from @mstead 
1. we need to delete stack derived pools
2. we need to revoke ents for derived pools were deleting.

**Comment by vritant** [comment]
3. need to list where deletePools is called and see if its okay to do this

**Comment by mstead** [comment]
> points from @mstead
> 1. we need to delete stack derived pools
> 2. we need to revoke ents for derived pools were deleting.

Delete stack derived pools in some cases. i.e when there is no other entitlement contributing to the stack.

While I agree with the issue when deleting expired pools, we need to make sure that we are deleting the right things.

**Comment by vritant** [comment]
- [ ] Delete stack derived pools in some cases. i.e when there is no other entitlement contributing to the stack.
- [ ] revoke ents for derived pools
- [ ] verify this logic should be in deletePools. what code paths call this method?

**Comment by vritant** [comment]
closed this against #1288

**Pull request closed without merging**
