### PR TITLE
ENT-1880: Port OwnerProductResource to spec-first

### PR DESCRIPTION
**Pull request by wolfdale**
- Updated schema file
- Updated OwnerProductResource API

### CODE REVIEW

**Comment by wolfdale** [comment]
@nikosmoum  @Ceiu @Januson  There is one issue, while porting `OwnerContentResource` & `OwnerProductResource` `(& OwnerResource)` the generated `OwnersApi` interface contains all the APIs (since all of them starts with `/owner/`) of `OwnerContentResource & OwnerProductResource (& OwnerResource)` making it difficult to implement the interface to respective classes as it enforces the rule to implement all the methods. Currently looking into alternatives to handle this.

**Comment by nikosmoum** [comment]
It doesn't look like openapi supports splitting the url paths into more than one generated interface, so the best course of action would be to merge the 3 *Resource files into one (OwnerResource.java), which would be preferable to another custom codegen or template change.

**Comment by Ceiu** [comment]
At the very least, we should probably put in an RFE to the OpenAPI project to allow specifying the interface for a given endpoint. I'm not a huge fan of those getting rolled into the owners interface, as it's already pretty bloated as it is.

**Comment by wolfdale** [comment]
@nikosmoum Made some new changes to the PR. 
Can you please take a look at this PR again.

**Comment by wolfdale** [comment]
Re-based the PR to resolve conflicts.

**Pull request merged**
