### PR TITLE
Fixing broken tests due to expiry date

### PR DESCRIPTION
**Pull request by mstead**

### CODE REVIEW

**Comment by mstead** [comment]
Still one reference to fix.

**Comment by mstead** [comment]
retest this please

**Comment by nguyenfilip** [comment]
Works for me on local machine. Will merge it as soon as hosted spec tests finish.

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
@mstead  The particular rspec-hosted tests that are failing on Jenkins are passing for me locally.

**Comment by nguyenfilip** [comment]
@mstead I am currently investigating the rspec-hosted failure. After I solve it I will merge this.

**Comment by nguyenfilip** [comment]
retest this please

**Pull request merged**
