### PR TITLE
Add utility to convert sync checkin report to async format

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by nguyenfilip** [comment]
Wrt spec test failure. You are hitting a timing issue that I fixed in #1364

**Comment by vritant** [comment]
@candlepin-pull-request-bot test this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by vritant** [comment]
@nguyenfilip can I add you as a reviewer?

**Comment by nguyenfilip** [comment]
@vritant Hm, what are the expected file formats? I thought that this is the expected sync report format:

```
{
  "testinghypervisor": [
    "42213396-7c72-46b2-3833-c7cc0ba1bb44",
    "42219aaa-c898-4aee-bd6e-a97541259a0b",
    "4221de5a-a5ae-5a71-5d72-53fc09617cc0",
    "4221ebc2-efc1-4b94-479a-d4297ec0ffac"
  ]
}

```

But the convertor doesn't work on this

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
@vritant the oracle failure is fine

**Comment by mstead** [comment]
Please add a comment as to what the script does and what it can be used for.

**Comment by vritant** [comment]
Perhaps I thought it useful then, but I dont see a lot of merit from this script any more, so I am closing this PR, if any one thinks its useful please let me know ill add it back

**Pull request closed without merging**
