### PR TITLE
Mstead/qpid connection fixes

### PR DESCRIPTION
**Pull request by mstead**
This PR addresses some of the connection issues that have been creeping up in Sat6.1

candlepin/gutterball will now reconnect if qpidd is restarted. They both allow configuring the number of times to retry, and the interval between retries.

Due to the reconnect fixes above, a couple of changes had to be made to gutterball to track messages that have already been processed. Qpidd seems to resend already processed messages on startup.

Fix for BZ 1200877 - The connection timeout is reproducible by importing a manifest containing a large subscription (Employee SKU) -- after 60 secs the exception was thrown.

### CODE REVIEW

**Comment by dgoodwin** [comment]
On GB startup while playing with things I am seeing this error which sounds like something you described, is this just due to having stuff floating around in queues?

2015-03-31 09:26:52,260 [Dispatcher-0-Conn-1] ERROR org.apache.qpid.client.BasicMessageConsumer - reNotification : Caught exception (dump follows) - ignoring...
java.lang.NullPointerException: null
        at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:70) ~[guice-persist-3.0.jar:na]
        at org.candlepin.gutterball.receiver.EventMessageListener.storeEvent(EventMessageListener.java:101) ~[EventMessageListener.class:na]
        at org.candlepin.gutterball.receiver.EventMessageListener.onMessage(EventMessageListener.java:62) ~[EventMessageListener.class:na]

**Comment by dgoodwin** [comment]
So does this literally still take 60 seconds to deliver a message when certain manifests are imported?

**Comment by dgoodwin** [comment]
service qpidd stop, queue up some events, re-start qpidd and they all get delivered, no errors in any logs. AWESOME. :+1:

**Comment by mstead** [comment]
> On GB startup while playing with things I am seeing this error which sounds like something you described, is this just due to having stuff floating around in queues?
> 
> 2015-03-31 09:26:52,260 [Dispatcher-0-Conn-1] ERROR org.apache.qpid.client.BasicMessageConsumer - reNotification : Caught exception (dump follows) - ignoring...
> java.lang.NullPointerException: null
> at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:70) ~[guice-persist-3.0.jar:na]
> at org.candlepin.gutterball.receiver.EventMessageListener.storeEvent(EventMessageListener.java:101) ~[EventMessageListener.class:na]
> at org.candlepin.gutterball.receiver.EventMessageListener.onMessage(EventMessageListener.java:62) ~[EventMessageListener.class:na]

Ya, this one is the hibernate startup issue that I mentioned last week. I couldn't reproduce it after I had these restart changes in place. A restart of qpidd will fix for now. I didn't think it was super critical for beta as there is a work around.

**Comment by mstead** [comment]
> So does this literally still take 60 seconds to deliver a message when certain manifests are imported?

No, it does take 60 secs to deliver that message. See the comment @ https://github.com/candlepin/candlepin/commit/2f14efc1988602609c76af178f47fc42e3839f74

**Comment by dgoodwin** [comment]
OK I can't break it, it looks good. I've tried some really big manifest as well. ACK.

**Pull request merged**
