### PR TITLE
sec: security test with GithubActions

### PR DESCRIPTION
**Pull request by sushicomabacate**

### CODE REVIEW

**Comment by sushicomabacate** [comment]
I sent the results of this test to site-security@redhat.com.

**Comment by Ceiu** [comment]
?????????????????????

**Comment by RSS1102** [comment]
> ?????????????????????

My repo has also undergone such testing by him..😕

**Comment by sushicomabacate** [comment]
> > ?????????????????????
> 
> My repo has also undergone such testing by him..😕

Thanks for the message, @RSS1102 
In your case, I have sent details at https://en.security.tencent.com/index.php/report/add

**Pull request closed without merging**
