### PR TITLE
CANDLEPIN-639: Add secret for I18n push

### PR DESCRIPTION
**Pull request by wottop**
How to test:
1. Check out the branch locally.
2. Clone the branch.
3. In the i18n.yml file matrix section: add the cloned branch to the branch list and the include list for Java versions.
4. Push the change to the cloned branch.
5. Protect the cloned branch to https://github.com/candlepin/candlepin/settings/branches. Do not check merge queue or status checks.
6. Run the i18n action on the cloned branch.
7. Note that the cloned branch will have a new version of the keys.pot file committed.

Note that the main branch will not succeed until this is merged. Both the merge queue and status check requirement will need to be taken off main for this to work.

### CODE REVIEW

**Comment by JoshAlbrecht23** [comment]
I created a branch off of your branch (jalbrech/2213261) and updated the i18n.yml to run the GH actions task on the jalbrech/2213261 branch. I then created a branch protection rule that is setup the same as the main branch.

- Require status check to pass before merging
- Require merge queue

Rule: https://github.com/candlepin/candlepin/settings/branch_protection_rules/40379543

Then I manually ran the i18n task in my branch, but I got the following errors when the i18n changes are being pushed:
```
remote: error: GH006: Protected branch update failed for refs/heads/jalbrech/2213261.        
remote: error: Changes must be made through the merge queue 9 of 9 required status checks are expected.    
```

https://github.com/candlepin/candlepin/actions/runs/5813056199/job/15759789605

When you tested, did the rule that you created for you branch match the one that I am using?

**Comment by wottop** [comment]
No. I did not put on the merge queue and status checks like main.
Still in progress. The changes here are not sufficient to get this to work.

**Comment by wottop** [comment]
This is ready based on the conversation about how we want the protections on main to be.

**Comment by wottop** [comment]
Unnecessary when merge queue and status test requirement are off.

**Pull request closed without merging**
