### PR TITLE
JSS work to merge to JSS feature branch - ENT-441

### PR DESCRIPTION
**Pull request by awood**
* Implementations of our streaming CRL code in JSS
* Separate many crypto related tasks into provider specific classes
* Modify checkstyle to use a suppression.xml file so we can later blacklist certain packages from production code but retain them in test code.

### CODE REVIEW

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
CertificateRevocationListTask:

* Before: 2.6s for 10541 revoked serials; 0.3G added to eden space (and then quickly GCed on next minor collection)
* After: 2.6s for 10561 revoked serials; 0.2G added to eden space

**Comment by mstead** [comment]
When deploying I needed to install the jss RPM before candlepin would install. We should add this to the dev docs.

**Comment by mstead** [comment]
**Before and After Certs**
@awood Here's the before and after certs that you requested. They should be appropriately named.

For the identity cert, I registered against master, then deployed the JSS candlepin and regenerated the cert via 'subscription-manager identity --regenerate' which should be sufficient. For the ent certs, I just attached in master and captured the cert, then removed it in JSS version and re-attached to the same pool.

[certs_before_and_after_jss.tar.gz](https://github.com/candlepin/candlepin/files/2106242/certs_before_and_after_jss.tar.gz)

**Comment by awood** [comment]
Consumer cert differences:
```
% diff -u <(openssl x509 -in consumer_cert_master.pem -noout -text) <(openssl x509 -in consumer_cert_jss.pem -noout -text)
--- /proc/self/fd/11	2018-06-15 09:51:56.649272649 -0400
+++ /proc/self/fd/12	2018-06-15 09:51:56.647272643 -0400
@@ -1,12 +1,12 @@
 Certificate:
     Data:
         Version: 3 (0x2)
-        Serial Number: 1887556989052876924 (0x1a31f314b1cd787c)
+        Serial Number: 7909865375425312207 (0x6dc57ca6936335cf)
     Signature Algorithm: sha256WithRSAEncryption
         Issuer: CN = bluestar, C = US, L = Raleigh
         Validity
-            Not Before: Jun 15 12:33:26 2018 GMT
-            Not After : Jun 15 13:33:26 2034 GMT
+            Not Before: Jun 15 12:39:41 2018 GMT
+            Not After : Jun 15 13:39:41 2034 GMT
         Subject: CN = becec805-7104-447c-9811-01cbdd56409d
         Subject Public Key Info:
             Public Key Algorithm: rsaEncryption
@@ -32,27 +32,27 @@
                     b5:5b
                 Exponent: 65537 (0x10001)
         X509v3 extensions:
+            X509v3 Key Usage: critical
+                Digital Signature, Key Encipherment, Data Encipherment
+            X509v3 Extended Key Usage: 
+                TLS Web Client Authentication
+            X509v3 Basic Constraints: 
+                CA:FALSE
             Netscape Cert Type: 
                 SSL Client, S/MIME
-            X509v3 Key Usage: 
-                Digital Signature, Key Encipherment, Data Encipherment
+            X509v3 Subject Key Identifier: 
+                EB:9C:E5:29:C6:05:09:7C:B4:F8:C4:57:83:08:F3:1E:80:A4:20:3D
             X509v3 Authority Key Identifier: 
                 keyid:6F:AF:C7:C2:C8:32:15:22:2D:7D:B0:5F:D0:93:75:1C:D1:B0:64:1F
-                DirName:/CN=bluestar/C=US/L=Raleigh
-                serial:B6:CE:33:28:24:04:D6:00
 
-            X509v3 Subject Key Identifier: 
-                EB:9C:E5:29:C6:05:09:7C:B4:F8:C4:57:83:08:F3:1E:80:A4:20:3D
-            X509v3 Extended Key Usage: 
-                TLS Web Client Authentication
             X509v3 Subject Alternative Name: 
                 DirName:/CN=becec805-7104-447c-9811-01cbdd56409d, DirName:/CN=bluestar
     Signature Algorithm: sha256WithRSAEncryption
-         36:53:b6:0f:7b:6e:25:25:a8:50:2f:07:58:29:1f:6b:71:de:
-         4c:50:0b:10:48:d3:22:e9:ef:07:9b:80:26:8b:23:f8:2f:f6:
-         50:6a:e9:6d:eb:d6:2c:51:cc:17:82:65:2a:0c:ad:88:16:66:
-         9c:e8:24:33:68:09:67:c9:0d:f3:b5:c9:1a:bd:4a:c8:9a:2c:
-         9e:22:34:22:87:6b:9b:21:92:35:d6:ca:e5:17:bb:c1:d1:80:
-         9c:32:7f:93:ff:9e:80:45:82:c7:c7:57:ca:2b:6f:07:a0:11:
-         b3:e9:2c:f7:aa:00:dd:42:c8:b2:ff:3e:c0:56:ba:7f:91:05:
-         c0:b3
+         6b:c2:3e:52:83:60:cc:a2:0e:6e:9a:03:92:12:8f:7f:88:2a:
+         f0:e7:fe:9b:4e:53:4a:fb:b7:42:dd:1a:10:13:7a:06:a0:16:
+         9c:d3:51:91:14:93:67:b3:69:94:dd:d2:08:79:0c:b8:f7:18:
+         ea:69:7a:76:da:4b:a8:a1:c3:ae:1d:e4:17:91:dc:d2:4d:4a:
+         e2:24:55:3e:85:92:99:82:11:07:41:0d:c5:ac:53:72:57:9b:
+         21:50:53:9b:12:2f:3f:e9:49:63:62:02:d0:28:f9:a1:8a:1a:
+         48:75:68:7c:48:2b:80:e2:cb:a3:59:2d:eb:5b:48:f4:bc:b7:
+         5e:e6
```
---
Entitlement cert differences:
```
% diff -u <(openssl x509 -in master_ent_cert.pem -noout -text) <(openssl x509 -in jss_ent_cert.pem -noout -text) 
--- /proc/self/fd/11	2018-06-15 09:53:25.336527368 -0400
+++ /proc/self/fd/12	2018-06-15 09:53:25.337527371 -0400
@@ -1,13 +1,13 @@
 Certificate:
     Data:
         Version: 3 (0x2)
-        Serial Number: 5129704495161237882 (0x47305f0f5ccf617a)
+        Serial Number: 8076588887716306678 (0x7015cecd41329ef6)
     Signature Algorithm: sha256WithRSAEncryption
         Issuer: CN = bluestar, C = US, L = Raleigh
         Validity
             Not Before: Jun 15 00:00:00 2018 GMT
             Not After : Jun 15 00:00:00 2019 GMT
-        Subject: CN = 19ec3d82613a4bd9a4bf1e63c1f667d9, O = admin
+        Subject: O = admin, CN = 0fcf8ca7512746af8b9880cc760e9cd4
         Subject Public Key Info:
             Public Key Algorithm: rsaEncryption
                 Public-Key: (2048 bit)
@@ -32,19 +32,21 @@
                     b5:5b
                 Exponent: 65537 (0x10001)
         X509v3 extensions:
+            X509v3 Key Usage: critical
+                Digital Signature, Key Encipherment, Data Encipherment
+            X509v3 Extended Key Usage: 
+                TLS Web Client Authentication
+            X509v3 Basic Constraints: 
+                CA:FALSE
             Netscape Cert Type: 
                 SSL Client, S/MIME
-            X509v3 Key Usage: 
-                Digital Signature, Key Encipherment, Data Encipherment
+            X509v3 Subject Key Identifier: 
+                EB:9C:E5:29:C6:05:09:7C:B4:F8:C4:57:83:08:F3:1E:80:A4:20:3D
             X509v3 Authority Key Identifier: 
                 keyid:6F:AF:C7:C2:C8:32:15:22:2D:7D:B0:5F:D0:93:75:1C:D1:B0:64:1F
-                DirName:/CN=bluestar/C=US/L=Raleigh
-                serial:B6:CE:33:28:24:04:D6:00
 
-            X509v3 Subject Key Identifier: 
-                EB:9C:E5:29:C6:05:09:7C:B4:F8:C4:57:83:08:F3:1E:80:A4:20:3D
-            X509v3 Extended Key Usage: 
-                TLS Web Client Authentication
+            X509v3 Subject Alternative Name: 
+                DirName:/O=admin/CN=0fcf8ca7512746af8b9880cc760e9cd4
             1.3.6.1.4.1.2312.9.6: 
                 ..3.3
             1.3.6.1.4.1.2312.9.8: 
@@ -52,11 +54,11 @@
             1.3.6.1.4.1.2312.9.7: 
                 ..
     Signature Algorithm: sha256WithRSAEncryption
-         bc:f7:68:ff:09:b2:23:47:6b:0c:54:59:5a:b4:c7:f8:9d:a1:
-         a7:06:65:3a:47:2e:b2:0b:79:d6:39:45:18:12:72:4d:29:86:
-         51:70:82:04:8c:ca:c2:97:d3:c2:b9:8f:ef:06:ac:8c:c1:f3:
-         9e:0c:8b:ac:05:9f:82:f0:99:ca:8f:7d:10:0a:2d:63:78:52:
-         47:93:de:cd:c2:c5:c5:f1:a5:d0:09:1e:fb:9d:b0:56:c4:27:
-         f0:a3:0a:48:73:f6:e7:9a:3a:e7:db:4d:b0:bc:f4:58:11:01:
-         eb:ad:ba:c0:c0:68:b5:4b:4e:25:8c:90:68:aa:e9:ca:d1:ff:
-         0c:23
+         28:61:71:b6:59:8f:f8:5e:54:ec:19:c0:c4:28:4e:df:47:31:
+         58:52:d9:e9:73:de:ae:97:03:1a:03:9b:e3:bb:22:ab:23:e2:
+         91:2b:c0:b9:d6:85:a9:54:52:a0:8c:01:b1:ba:20:5a:00:ae:
+         e3:79:85:22:43:aa:25:6e:0d:cb:73:dd:8a:ca:f8:c3:ff:6e:
+         01:74:25:6d:42:bb:af:fa:ca:28:59:c3:66:f4:5f:77:e3:a6:
+         2a:7f:c8:d0:fb:0b:72:f9:a5:93:da:10:a5:7b:29:a2:9c:4c:
+         70:02:c4:5b:b6:8b:47:0c:23:5c:94:87:37:71:67:1d:eb:b2:
+         6e:ca
```

**Comment by mstead** [comment]
**Round 2 Files**
@awood I've added an extra identity cert this time. One is regenerated in JSS candlepin from the original and the other is from a net new registration
[2_certs_before_and_after_jss.tar.gz](https://github.com/candlepin/candlepin/files/2106313/2_certs_before_and_after_jss.tar.gz)

**Comment by awood** [comment]
There are several differences between the certificates.
## Identity Certificate
* The Key Usage extension is now marked critical.  This is acceptable.  [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.3) states that Key Usage SHOULD be marked critical.
* The Authority Key Identifier no longer has the DirName and Serial attributes.  The RFC states "The identification MAY be based on either the key identifier (the subject key identifier in the issuer's certificate) **or** the issuer name and serial number" (emphasis mine).  I don't think it's wrong to have all 3 attributes, so I will make that change but the *or* in the language is what lead me to initially just include only the keyid.
* The Basic Constraints extension is now included.  The RFC says "This extension MAY appear as a critical or non-critical extension in CA certificates that contain public keys used exclusively for purposes other than validating digital signatures on certificates."  So including it is fine.
## Entitlement Certificate
* The Subject DN is rearranged.  I don't see any restrictions on the ordering in the RFC but I like the new way better actually since the CN is more specific than the O.
* Key Usage is critical here too.
* Basic Constraints added here too.
* Authority Key Identifier is missing DirName and serial here too.
* SubjectAlternativeNames have been added to the certificate.  This is wrong.  The SubjectAltNames should only be added to identity certificates.  It doesn't hurt to have it, but it doesn't make any sense semantically.
* Most importantly, the 1.3.6.1.4.1.2312.9.7 extension with content information has changed.
  ```
  -                .#x.K.)O.,f(H,.`.K-K-bH..g..]I.......
  +                ."x.K.)O.,f(H,.`.K-K-bH..g..]I......
  ```
  The first two characters in the output represent the tag (unprintable in this case) and length of the extension.  Looking on an ASCII table, I see the *#* character is 35 and the *"* character is 34 which accords with what we see visually: the new extension is one byte shorter.  This discrepancy needs to be investigated.

**Comment by mstead** [comment]
Functionally I don't see anything wrong with this PR, though as we talked about in scrum, it is very difficult to test against an actual CDN. Once the remaining items above are addressed, we should try and get a build to IT to test the certs against the CDN.

**Comment by awood** [comment]
I'm actually going to leave the issuer and serial out of the AuthorityKeyIdentifier.
* Having them there makes it difficult to [recreate a CA cert](https://www.v13.gr/blog/?p=293).  Arguably, you shouldn't be doing this in the first place.  Key re-use is generally discouraged/
* More importantly, the semantics of that extension are confusing enough to warrant an entry on the OpenSSL [FAQ](https://www.openssl.org/docs/faq.html#USER14)

**Comment by awood** [comment]
@mstead those two entitlement certificates you posted: are they by chance generated by running a spec test?  I'm running `master` a couple times and dumping the cert after running a spec test (`rspec:entitlement_certificate_v3:'correct body`).  The extension value changes slightly each time.

```
[HEX DUMP]:044478DA1DCA410E00100C04C07D8C8F512B9A08D236DE4F5C27934A7666938EE5B0CE81AA1EF8E29BA24D05B26670069271F0FD43C30538B513D009DE163AE970E9215F0B70

[HEX DUMP]:044478DA1DCA410E00100C04C07D8C8F512B9A08D236DE4F5C27934A7666938EE5B0CE81AA1EF8E29BA24D05B26670069271F0FD43C30538B513D009D0AA749F178EBE2E05B0
```

The majority of it is the same but it differs towards the end.  I imagine this is some artifact of the testing process.  Perhaps some randomization of the data during testing?  That's just speculation on my part.

I will try a strictly apples-to-apples comparison Monday.  E.g. entitle a system, download the certificate, force regeneration of the entitlement, then download the certificate again.  I wonder if the extension values are still different when using master both times.  I can redeploy with the JSS branch and then dp the same thing.

**Comment by mstead** [comment]
> @mstead those two entitlement certificates you posted: are they by chance generated by running a spec test? I'm running master a couple times and dumping the cert after running a spec test (rspec:entitlement_certificate_v3:'correct body). The extension value changes slightly each time.

@awood No, I didn't generate them via a spec test. I deployed master, registered a system and consumed an ent and copied the cert. Then I removed all ents before deploying the JSS version of candlepin. At that point, I just attached an ent from the same pool.

**Comment by mstead** [comment]
@awood Here's the before and after of the 1.0 certs. Same output from rct in this case as well.

[1.0-certs.tar.gz](https://github.com/candlepin/candlepin/files/2111723/1.0-certs.tar.gz)

**Comment by awood** [comment]
@mstead after looking, the differences between the v1 certs don't concern me.  Just differences in ordering and some differences that I think are actual improvements.  I'll keep digging into the v3 differences.

**Comment by awood** [comment]
I think the v3 differences in the `1.3.6.1.4.1.2312.9.7` extension are unrelated to these changes.
* I see slightly different values (usually the last four or five bytes) when attaching to the same product multiple times.
* The relevant code changed from
   ```java
   byte[] value = wrapper.getValue() == null ? new byte[0] :wrapper.getValue();
   certGen.addExtension(wrapper.toASN1Primitive(), wrapper.isCritical(),
       new DEROctetString(value));
   ```
   to
   ```java
   byte[] value = wrapper.getValue() == null ? new byte[0] : wrapper.getValue();
   OCTET_STRING der = new OCTET_STRING(value);
   certExtensions.add(buildCustomExtension(wrapper.getOid(), wrapper.isCritical(), der));

   [...]
   private Extension buildCustomExtension(String oid, boolean critical, ASN1Value der) throws IOException {
       byte[] extnValue = ASN1Util.encode(new OCTET_STRING(ASN1Util.encode(der)));
       return new Extension(new ObjectIdentifier(oid), critical, extnValue);
   }
   ```
   The new code is wrapping the extension octet string inside of another octet string which is exactly what BouncyCastle ends up doing in ExtensionsGenerator:
   ```java
   public void addExtension(
        ASN1ObjectIdentifier oid,
        boolean              critical,
        ASN1Encodable        value)
        throws IOException
    {
        this.addExtension(oid, critical, value.toASN1Primitive().getEncoded(ASN1Encoding.DER));
    }

    /**
     * Add an extension with the given oid and the passed in byte array to be wrapped in the
     * OCTET STRING associated with the extension.
     *
     * @param oid OID for the extension.
     * @param critical true if critical, false otherwise.
     * @param value the byte array to be wrapped.
     */
    public void addExtension(
        ASN1ObjectIdentifier oid,
        boolean              critical,
        byte[]               value)
    {
        if (extensions.containsKey(oid))
        {
            throw new IllegalArgumentException("extension " + oid + " already added");
        }

        extOrdering.addElement(oid);
        extensions.put(oid, new Extension(oid, critical, new DEROctetString(value)));
    }
   ```
   The old code called into that top method that accepts an ASN1Encodable with a DEROctetString object which is then encoded and wrapped inside another DEROctetString.  This is all due to the fact that X.509 extension values are required to be octet strings, and that's it.  If you want whatever the extension value is to be ASN.1 parseable after you enter that octet string, it's on you to encode it that way.

**Comment by awood** [comment]
> This is all due to the fact that X.509 extension values are required to be octet strings, and that's it. If you want whatever the extension value is to be ASN.1 parseable after you enter that octet string, it's on you to encode it that way.

Note that I don't think our Huffman tree *needs* to be ASN.1 parseable,  It's actually redundant.  Usually the additional encoding is performed when the extension value is expected to be an ASN.1 sequence or something.  But the ship has sailed long ago on that decision.

**Comment by mstead** [comment]
@awood @kahowell Based on the info above, I think that this PR is ready to merge. Thoughts?

**Comment by awood** [comment]
Yep.  This will merge to a feature branch that I'll rebase on master once this PR lands.

**Pull request merged**
