### PR TITLE
[2.0] Added a valid checksum to a problematic Liquibase changeset

### PR DESCRIPTION
**Pull request by Ceiu**
- Added a valid checksum to the consumer ID fact index changeset
  to fix an issue where Liquibase would detect an a mismatch when
  the changeset was actually valid

### CODE REVIEW

**Comment by Ceiu** [comment]
This addresses a minor annoyance I run into whenever testing a database from any Sat install. For some reason, this particular changeset always complains, even though it's perfectly fine. In the past, I've simply updated the checksum in the DB directly and moved on, but I'm too lazy to do even that anymore.

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
performance ok

**Comment by wottop** [comment]
ack

**Pull request merged**
