### PR TITLE
Authenticate over SSL only

### PR DESCRIPTION
**Pull request by nguyenfilip**
Candlepin shouldn't send WWW-Authenticate when the client communicates using
insecure channel, instead Candlepin should send back 403 Forbidden

### CODE REVIEW

**Comment by awood** [comment]
Instead of a 403, I'm thinking either a 400 or maybe a 301 or 308?  But otherwise looks good!

**Comment by nguyenfilip** [comment]
I used 400. Thanks!

**Comment by awood** [comment]
@nguyenfilip Looks good.  One final thought: should we allow this check to be disabled via a config value (where the SSL check defaults to on)?  I can see some utility in allowing Candlepin to be deployed over HTTP to allow for easier debugging.  With the SSL check always on, that wouldn't be possible.

**Comment by nguyenfilip** [comment]
@awood Good idea! Added the config option.

**Comment by awood** [comment]
:tada:  Nice work!

**Pull request merged**
