### PR TITLE
[2.0] 1502807: bind with an empty string as POST body

### PR DESCRIPTION
**Pull request by vritant**
ConsumerResource.bind should NEVER be provided with a POST body. While technically that change would be backwards compatible,  there are older clients which erroneously provide an empty string  as a post body and hence result in a serialization error.
 ref: BZ: 1502807

### CODE REVIEW

**Comment by vritant** [comment]
[1502807 : 2.0 bind with empty string body in ConsumerResource](https://trello.com/c/XaETyLUC/597-1502807-20-bind-with-empty-string-body-in-consumerresource)

**Comment by vritant** [comment]
@mstead : the mysql rspec failure is this:

> 15:50:04   1) Standalone Virt-Limit Subscriptions should revoke guest entitlements when migration happens
15:50:04      Failure/Error: @guest1_client.list_entitlements.length.should == 0
15:50:04 
15:50:04        expected: 0
15:50:04             got: 1 (using ==)
15:50:04      # ./server/spec/virt_spec.rb:220:in `block (2 levels) in <top (required)>'

this is a unrelated non-determinstic failure , and I reproduced this is the target branch candlepin-2.0-HOTFIX as well, after some tries.

**Comment by vritant** [comment]
The postgres test failed with:

> 15:55:23 ERROR: for rspecjenkinscandlepincandlepinpullrequestspectestshostedpostgresql202_db_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
15:55:23 An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
15:55:23 If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
15:55:23 return value: 0

jenkins issues imo.

**Comment by mstead** [comment]
NOTE: I've tested this PR with a broken version of subman/python-rhsm and it addresses the issue.

**Pull request merged**
