### PR TITLE
1363701: duplicate key value violates unique constraint on product-content

### PR DESCRIPTION
**Pull request by vritant**
We hit this bug: 
https://vladmihalcea.com/2013/10/16/hibernate-facts-knowing-flush-operations-order-matters/

following are the logs after we force a flush, we can see the same record is deleted and then inserted again. Without the flush we would insert first:

2017-02-27 08:37:44,281 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] DEBUG org.hibernate.SQL - delete from cp_product_content where product_id=? and content_id=?
2017-02-27 08:37:44,281 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [VARCHAR] - 276
2017-02-27 08:37:44,281 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [2] as [VARCHAR] - 5177
2017-02-27 08:37:44,282 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] DEBUG org.hibernate.SQL - delete from cp_product_content where product_id=? and content_id=?
2017-02-27 08:37:44,282 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [VARCHAR] - 276
2017-02-27 08:37:44,282 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [2] as [VARCHAR] - 5176

2017-02-27 08:37:44,283 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] DEBUG org.hibernate.SQL - insert into cp_product_content (product_id, content_id, enabled, created, updated) values (?, ?, ?, ?, ?)
2017-02-27 08:37:44,283 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [VARCHAR] - 276
2017-02-27 08:37:44,283 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [2] as [VARCHAR] - 5177
2017-02-27 08:37:44,283 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [3] as [BOOLEAN] - false
2017-02-27 08:37:44,283 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [4] as [TIMESTAMP] - <null>
2017-02-27 08:37:44,283 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [5] as [TIMESTAMP] - <null>

### CODE REVIEW

**Comment by mstead** [comment]
@vritant Do you know if this change has any affect on import performance? I'm mostly concerned in cases where there are a lot of products and content sets.

**Comment by mstead** [comment]
retest this please

**Comment by vritant** [comment]
test this please

**Comment by barnabycourt** [comment]
@vritant Any comments on the performance implications per the question from @mstead

**Comment by vritant** [comment]
@barnabycourt I spoke to @mstead offline, and the results were better than current candlepin-0.9.54-HOTFIX . @mstead is this okay to merge?

**Comment by mstead** [comment]
ACK - Looks good.

**Pull request merged**
