### PR TITLE
fetching consumer's entitlements should not calc attributes

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by vritant** [comment]
Note: this can't be pulled in yet. I'm trying to verify this change does not break subscriptions. please feel free to merge if you get there before me!

**Comment by vritant** [comment]
@dgoodwin was able to register and consume a pool against this code. any thing else I should verify?

**Comment by wottop** [comment]
please rebase to master

**Comment by wottop** [comment]
entitlement_spec.rb: should have pool type calculated attribute
fails with 
Failure/Error: ents[0]['pool']['calculatedAttributes']['compliance_type'].should == 'Standard'

**Comment by vritant** [comment]
closing this, will open another one off of the candlepin org's repo

**Pull request closed without merging**
