### PR TITLE
[2.1] Added the new Traceable and TraceableParam annotations

### PR DESCRIPTION
**Pull request by Ceiu**
- Added the new Traceable and TraceableParam annotations, to denote
  large, complex or messy methods likely to be hotspots to be
  explicitly measured in profiling tools
- Tagged a handful of methods with the new annotations:
  - CandlepinPoolManager.refreshWithRegeneration
  - CandlepinPoolManager.deletePools
  - CandlepinPoolManager.revokeEntitlements
  - ContentManager.importContent
  - KingpinJob.execute
  - ProductManager.importProducts

### CODE REVIEW

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
Ready once Jenkins passes

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by barnabycourt** [comment]
performance ok

**Pull request merged**
