### PR TITLE
1382307: Expose verify_ssl, default localhost to NONE

### PR DESCRIPTION
**Pull request by kahowell**
This was IMO a less invasive change than having the deployment scripts
specify the cert to verify against.

This fixes developer deployment against newer ruby versions.

### CODE REVIEW

**Comment by nguyenfilip** [comment]
You are hitting the same timing spec test issue as I do. Prepared #1364 to address that

**Comment by kahowell** [comment]
@nguyenfilip ack. I rebased on master, since #1364 has been merged :smile:

**Comment by nguyenfilip** [comment]
retest this please

**Comment by barnabycourt** [comment]
@nguyenfilip This has now passed all tests, do you have any further review for it?

**Pull request merged**
