### PR TITLE
Update checkstyle jars and correct issues [ENT-4863]

### PR DESCRIPTION
**Pull request by wottop**
An attempt to use a patch previously submitted against the checkstyle repo solved some of these violations but caused others. In light of the headache that maintaining our own spin of the jar would cause, it seems more prudent to make the few corrections needed in the code. The rule definition in checkstyle.xml is not granular enough to account for the scenarios.

Perhaps this is just a temporary bridge to some other code-style tool, like spotless.

### CODE REVIEW

**Review by JoshAlbrecht23 — APPROVED** [review]

**Review by nikosmoum — APPROVED** [review]
This workaround is really ugly, but it can't be helped for now I guess.

**Comment by Ceiu** [comment]
Did we explore adding a custom check that exists outside the jar, or bumping the issue with the checkstyle folks?

**Comment by nikosmoum** [comment]
I left a comment in that github issue, but I wouldn't expect much of it given it's been open for more than a year already

**Comment by nikosmoum** [comment]
They're response is 'PRs are welcome'

**Pull request merged**
