### PR TITLE
1354633: Cleanup stray ueber objects

### PR DESCRIPTION
**Pull request by mstead**
An old bug that caused the ueber cert pools
to be deleted was fixed but did not correct
the state of any owners that were affected.
All required ueber objects (sub, product,
content, consumer) were not cleaned up.

Subsequent attempts to get or create a new
debug cert would fail because the data was
in a new state.

This patch adds a new liquibase changeset to
clean up the data. This patch plus the old
bug fix should make sure that this doesn't
happen again.

## Testing Details

**Before starting, make sure that you have a manifest handy! You will have to import it in one of the steps below!!!**

1) Check out the branch that first introduced the bug and deploy.
```bash
$ git co -b ueber-broken 64b74191499e60de17162f56e10a090c74de5b87
$ bin/deploy -gt
```
2) Generate the debug cert for the 'admin' owner.
```bash
$ curl -X POST -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
```
3) Import a manifest and then attempt to GET the existing ueber cert to trigger the OLD bug. It should complain about an IndexOutOfBounds or something of the likes.
```bash
$ ./cpc import admin /path/to/your/manifest.zip
$ curl -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
```
4) Check out the HEAD of candlepin-0.9.54-HOTFIX and redeploy leaving the DB unchanged.
```bash
$ git co -b 0954-debug-old-fix-applied --track origin/candlepin-0.9.54-HOTFIX
$ bin/deploy
```
5) After redeploying with the fix, create a new owner and generate a debug cert for it. Verify that the new owner can create and get the new cert but the old still can't because of the bad data.
```bash
# Should fail with the same error
$ curl -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
# Do another post to REALLY mess things up. The POST will indeed create a new cert for you
# but trying to fetch it breaks becuse there are now 2 ueber consumers!!!!!
$ curl -X POST -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
$ curl -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert

# Create new owner and verify POST and GET works.
$ ./cpc create_owner zombie
$ curl -X POST -k -u admin:admin https://localhost:8443/candlepin/owners/zombie/uebercert
$ curl -k -u admin:admin https://localhost:8443/candlepin/owners/zombie/uebercert

6) At this point you are in the state that our katello friend had his system in. Let's test
the patch! Checkout the branch for this PR. Simply redeploy this patched version of
candlepin and liquibase will kick in, clean out all the bogus data, and should leave
BOTH owners in a state to be able to create and get certs without any issues. Run
POST as much as you'd like and all should be well with only one copy of the ueber
objects in the DB per owner.
```bash
# ALL OF THESE SHOULD WORK WITHOUT ISSUES
$ curl -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
$ curl -X POST -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
$ curl -X POST -k -u admin:admin https://localhost:8443/candlepin/owners/admin/uebercert
$ curl -k -u admin:admin https://localhost:8443/candlepin/owners/zombie/uebercert
$ curl -X POST -k -u admin:admin https://localhost:8443/candlepin/owners/zombie/uebercert
```

### CODE REVIEW

**Comment by Ceiu** [comment]
Looks good. Tests were verified every step of the way. This PR branch indeed addresses the IndexOutOfBoundsException and the unique result returning multiple rows issue.

I restarted the Jenkins jobs for the two failing tests, so hopefully it was just a hiccup there and we can merge once those clear.

**Comment by mstead** [comment]
Pulled in a commit from 0951 to see if it fixes the mysql test issues. I'll revert it if it has no impact.

**Comment by Ceiu** [comment]
Looks good with the update. Merging.

**Comment by jhutar** [comment]
Hello all :-) I would like to test this on Satellite 6 (that means using rpms, not git checkouts). What is that "./cpc" utility and where can I get it please? Or is there some way how to reproduce without using it?

**Comment by mstead** [comment]
The cpc utility is a ruby CLI client utility that we primarily use for hitting the candlepin API in our rspec tests. Testing these steps as they are above would require you to enable basic auth to candlepin as satellite auth to candlepin is done via OAuth.

To test this on a satellite:
1. Import a manifest into an org
2. Select 'Manage Organizations' and 'Edit' the org above.
3. Click the 'Generate and Download' button to download the debug certificate.
4. Refresh the manifest:
      * Navigate to Content -> Red Hat Subscriptions
      * Click 'Manage Manifest'
      * Click 'Refresh Manifest'
5. Repeat steps 2-3 to attempt to re-download the debug certificate.

Results after step 5:
```json
{
  "error": {"message":"Katello::Resources::Candlepin::Owner: 500 Internal Server Error {\"displayMessage\":\"Runtime Error Index: 0, Size: 0 at java.util.ArrayList.rangeCheck:635\",\"requestUuid\":\"e09c4eff-175c-49e4-b1e7-2f41bfcbffb7\"} (GET /candlepin/owners/mtest/uebercert)"}
}
```

**Comment by jhutar** [comment]
Thank you very much!

**Pull request merged**
