### PR TITLE
[M] Fixed product creation order in test data importer (ENT-3552)

### PR DESCRIPTION
**Pull request by Ceiu**
- The Candlepin test data importer will now resolve product references
  to ensure products are created in the right order during test data
  import
- Changed product certificate generation such that any unexpected
  exception results in an InternalServerError rather than a null
  certificate

### CODE REVIEW

**Review by wolfdale — APPROVED** [review]
ack

**Review by nikosmoum — CHANGES_REQUESTED** [review]
Ack, but let's add the bz id in the commit message: 1928249

**Comment by nikosmoum** [comment]
Also, there seems to be a related unit test failure

**Comment by Ceiu** [comment]
Done. I've updated the commit message, but haven't yet addressed the test failure. Looking into that now.

**Comment by Ceiu** [comment]
Test fixed. This also changed a bit of the logic in the product cert stuff. The convention I've landed on is:
- If it's a product that can have a cert, and that cert generation failed, throw an exception
- if the product cannot have a cert (following our numeric-id = engineering product logic), then the generation always returns null.

The affected test has been updated accordingly.

**Review by nikosmoum — APPROVED** [review]

**Pull request merged**
