### PR TITLE
Pruned unused methods and javadocs updates for ProductServiceAdapter (2.0)

### PR DESCRIPTION
**Pull request by mstead**
This PR is combination of updating the docs and pruning unused methods in 2.0.

### CODE REVIEW

**Comment by Ceiu** [comment]
Looks good, but there's still a few ambiguous things in a number of the methods. Specifically, what should happen if null is passed in for a product or content (throw an exception? do nothing? return null?).

**Comment by mstead** [comment]
> Looks good, but there's still a few ambiguous things in a number of the methods. Specifically, what should happen if null is passed in for a product or content (throw an exception? do nothing? return null?).

Ok thanks. I'll add that stuff as well.

**Comment by awood** [comment]
@mstead  Is this ready to be merged?

**Comment by mstead** [comment]
> @mstead Is this ready to be merged?

Not yet. I keep forgetting about this. I'll try and get this done today.

**Comment by mstead** [comment]
REMINDER TO MYSELF: Put this in 0.9.54 as well.

**Comment by Ceiu** [comment]
Nice. Less stuff to maintain is always more gooder.

ACK

**Pull request merged**
