### PR TITLE
Revoke performance fix

### PR DESCRIPTION
**Pull request by nguyenfilip**
Persistent collection Pool.entitlements has been set to EXTRA Lazy. That was
causing serious performance degradation when removing from that collection.
Specifically the removal from that collection in CandlepinPoolManager could take
as much as 8 seconds for big data sets.

### CODE REVIEW

**Comment by barnabycourt** [comment]
@vritant @nguyenfilip what is the impact on the overall performance suite with this change to the revoke?

**Comment by nguyenfilip** [comment]
@barnabycourt testing right now, created the PR to make sure the tests are passing everywhere

**Comment by nguyenfilip** [comment]
@barnabycourt @vritant I am still testing performance increase of this fix for the specific scenario.

**Comment by nguyenfilip** [comment]
@Ceiu @mstead @vritant ok, the problem during import is not only the EXTRA lazy annotation. Also the recent providedProduct caused a massive performance regression in this code path. 

CandlepinPoolManager.sendDeletedEvents takes forever, because before serializing the deleted entitlements it is filling out all the Pool.providedProduct products (about 21k collections here)

**Comment by mstead** [comment]
Made a change on Friday that improves the event data serialization drastically. The total time for an import for our problem test data went down to ~15 minutes. There are still some hot spots, but overall this isn't bad.

```json
{
  "id" : "import_c8d524cb-1e86-4098-9480-3ded6e0a1a1c",
  "state" : "FINISHED",
  "startTime" : "2016-11-25T19:31:44+0000",
  "finishTime" : "2016-11-25T19:47:56+0000",
  "result" : "org.candlepin.model.ImportRecord@1f1d1b02",
  "principalName" : "admin",
  "targetType" : "owner",
  "targetId" : "customer",
  "ownerId" : "customer",
  "resultData" : "[cloaked]",
  "statusPath" : "/jobs/import_c8d524cb-1e86-4098-9480-3ded6e0a1a1c",
  "done" : true,
  "group" : "async group",
  "created" : "2016-11-25T19:31:44+0000",
  "updated" : "2016-11-25T19:47:56+0000"
}
```

**Commit Message**
Removed the useage of ProductCachedSerializationModule in
EventFactory while serializing pools since we use the
HATEOS JSON version of Pool when serializing for Events.

Removing this serializer produces the exact same JSON
data. No need to hydrate provided products as it is
never, and has never, been included.

**Comment by barnabycourt** [comment]
@vritant How did the performance suite respond to this fix? Is everything still playing nice with the other actions?

**Comment by vritant** [comment]
Nack Based on the performance results.

**Comment by mstead** [comment]
I'll be looking into this more today.

**Comment by mstead** [comment]
Closing as this was addressed by 1429.

**Pull request closed without merging**
