### PR TITLE
Awood/resteasy3

### PR DESCRIPTION
**Pull request by awood**
This PR does not provide any new functionality so there is nothing new to test.  The spec tests should continue to pass exactly as they did before.

### CODE REVIEW

**Comment by awood** [comment]
jenkins-bot, retest this please

**Comment by awood** [comment]
jenkins-bot, retest this please

**Comment by wottop** [comment]
I had to run bundle install to get the new gems. This modifies my local Gemfile.lock. Should this file be in source control?

**Comment by awood** [comment]
> I had to run bundle install to get the new gems. This modifies my local
> Gemfile.lock. Should this file be in source control?

Can you post the diff? To answer your question the Gemfile.lock file
should normally be checked in, but I thought I had done that.

**Comment by wottop** [comment]
diff --git a/Gemfile.lock b/Gemfile.lock
index e132538..241baa5 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -78,6 +78,3 @@ DEPENDENCIES
   rest-client (~> 1.6.0)
   rspec
   stringex
-
-BUNDLED WITH
-   1.10.6


its just me. nm.

**Comment by wottop** [comment]
ack

**Pull request merged**
