### PR TITLE
List owner entitlements

### PR DESCRIPTION
**Pull request by vritant**
* fix refresh pool spec tests
* refactor entitlement curator to allow searching for entitlements by owner, consumer, or all.
* clean up refactor entitlement
* add junit tests for resources and entitlement curator
* update owner/{key}/entitlements API to paginate and search by product, attributes, etc
* add spec tests for update of owner entitlements API ( not done yet )

### CODE REVIEW

**Comment by dgoodwin** [comment]
ok to test

**Comment by vritant** [comment]
@dgoodwin I have a concern with this change. this API aleady existed, and there was no regeneration of dirty entitlements when the API was called. while the API change is backwards compatible, the default behavior has changed to regenerate all the dirty entitlements. this could be potentially expensive for the entire owner organization.

I could change default behavior to NOT regenerate by default, but I don't thing that is desired. thoughts?

**Comment by Ceiu** [comment]
retest this please

**Comment by dgoodwin** [comment]
@vritant I would think this API should not regenerate dirty entitlements, it's not a client API call to fetch certs so regenerating them here will probably do something unintentional and break more systems holding the old certs.

**Comment by vritant** [comment]
@dgoodwin removed regem
@Ceiu done

**Comment by vritant** [comment]
@Ceiu oops, spoke too soon. forgot the junit tests

**Comment by vritant** [comment]
retest this please

**Comment by vritant** [comment]
retest this please

**Comment by wottop** [comment]
ack

**Pull request merged**
