### PR TITLE
Swagger Annotations

### PR DESCRIPTION
**Pull request by nguyenfilip**
Annotations on our resources that enable generating Swagger file. Also updating
swagger-ui library to the latest version.

### CODE REVIEW

**Comment by barnabycourt** [comment]
Is there a way to have the listing show up in alphabetical order?

**Comment by barnabycourt** [comment]
When looking at the "jobs" api endpoint and clicking on "Model" it shows:
```
Inline Model [
Inline Model 1
]
Inline Model 1 {...
```
Is there a way to have something more meaningful there than Model & Model1?

**Comment by barnabycourt** [comment]
I do not believe the root resource should be included in the list.

**Comment by nguyenfilip** [comment]
@barnabycourt Removed Root resource. The problem you saw with 'Model 1' was a problem in Swagger UI javascript. I upgraded (yet again) to the newest swagger-ui and that fixes the issue. Right now in Jobs resource I can see: 

```
Inline Model [
  JobStatus
]

JobStatus {
```

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
I think that the test failures are caused by unclean working copy of Candlepin in our docker images. Prepared #1236 to address this. Will need to talk to maintainer of our docker images to verify this.

**Comment by barnabycourt** [comment]
@candlepin/jenkins-bot test this please

**Comment by nguyenfilip** [comment]
@barnabycourt after you merge this, I will create a PR to merge the dev branch into the master. This is the final Swagger PR.

**Pull request merged**
