### PR TITLE
1451032: Allow tomcat to read /etc/candlepin

### PR DESCRIPTION
**Pull request by kahowell**

### CODE REVIEW

**Comment by barnabycourt** [comment]
The test likely failed because candlepin needs access to /var/lib/candlepin in order to write the CRL file which defaults to /var/lib/candlepin/candlepin-crl.crl

**Comment by mstead** [comment]
retest this please

**Comment by kahowell** [comment]
>The test likely failed because candlepin needs access to /var/lib/candlepin in order to write the CRL file which defaults to /var/lib/candlepin/candlepin-crl.crl

@barnabycourt, doesn't look like we mess with the context for `/var/lib/candlepin`... and on my machine at least it ended up as `system_u:object_r:tomcat_var_lib_t:s0`, so I think we're probably okay on that front, but I did not think to check that previously, so thanks.

**Comment by kahowell** [comment]
db8a12f..e4de42e:
 - added /var/{cache,lib,log}/candlepin rules
 - use macros for permissions
 - add missing rule

**Comment by kahowell** [comment]
e4de42e..e0a8fcb: add restorecon for new rules

**Comment by kahowell** [comment]
e0a8fcb..183ac13: Fix BZ# in commit message

**Pull request merged**
