### PR TITLE
1286697: Fix issue with cascaded deletes on pools.

### PR DESCRIPTION
**Pull request by awood**

### CODE REVIEW

**Comment by awood** [comment]
@nguyenfilip Do we need to remove the `LazyCollection(LazyCollectionOption.EXTRA)` annotation that you mentioned in the bug?  Or is the annotation fine but the bug only manifests when it is removed?

**Comment by vritant** [comment]
Note: removeEntitlement method is being replaced in the batch revoke PR.

**Comment by nguyenfilip** [comment]
@awood It only manifests if it is removed. I don't think we should remove that annotation right now.

**Comment by Ceiu** [comment]
@candlepin/jenkins-bot retest this please

**Comment by awood** [comment]
@nguyenfilip Does this issue still need addressing with the batch revoke stuff merged in now?  I added `orphanRemoval` but `ConsumerResourceVirtEntitlementTest` fails now because presumably I'm not doing a flush somewhere.

**Pull request closed without merging**
