### PR TITLE
[2.5] 1687894: Expose useful data on System Purpose Compliance event; ENT-1210

### PR DESCRIPTION
**Pull request by nikosmoum**

### CODE REVIEW

**Comment by nikosmoum** [comment]
@jturel Hey, here is the 2.5 backport PR. I tried to add you to assignees or reviewers, but github won't let me do that any more for some reason (looks like I can only add people in the Candlepin group).

**Comment by jturel** [comment]
Thanks Nikos! I'll let you know as soon as I confirm the functionality

**Comment by jturel** [comment]
@nikosmoum finally got some time to build locally and test it out. I see that the new fields are in the event and they should get the job done for me. This is good to merge.

**Comment by kahowell** [comment]
> I tried to add you to assignees or reviewers, but github won't let me do that any more for some reason (looks like I can only add people in the Candlepin group).

@jturel @nikosmoum , I added jturel as a collaborator on the repo. Once he accepts, we'll see if we can request reviews. I just want to figure out what a good process is for this.

**Comment by Ceiu** [comment]
ack

**Pull request merged**
