### PR TITLE
1212122: Last checkin date was getting returned in create json, but n…

### PR DESCRIPTION
**Pull request by wottop**
…ot getting persisted

### CODE REVIEW

**Comment by dgoodwin** [comment]
**Build Log**
*last 10 lines*

 ```
[...truncated 11356 lines...]
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: chainsaw@redhat.com
IRC notifier plugin: Sending notification to: #candlepin
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of a7bc0283587bdc38881cc3612096e340d9845abe to FAILURE with url http://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/candlepin-docker-unittest-pullrequest/490/ and message: 'Build finished.'
```

**Comment by wottop** [comment]
retest this please

**Comment by dgoodwin** [comment]
**Build Log**
*last 10 lines*

 ```
[...truncated 11362 lines...]
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: chainsaw@redhat.com
IRC notifier plugin: Sending notification to: #candlepin
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of a7bc0283587bdc38881cc3612096e340d9845abe to FAILURE with url http://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/candlepin-docker-unittest-pullrequest/494/ and message: 'Build finished.'
```

**Comment by wottop** [comment]
working on unit tests

**Comment by dgoodwin** [comment]
**Build Log**
*last 10 lines*

 ```
[...truncated 11361 lines...]
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: chainsaw@redhat.com
IRC notifier plugin: Sending notification to: #candlepin
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of 53963b3dbb19af9874e58dfb2de7027f507a51b5 to FAILURE with url http://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/candlepin-docker-unittest-pullrequest/495/ and message: 'Build finished.'
```

**Comment by Ceiu** [comment]
ACK

**Pull request merged**
