### PR TITLE
[2.1] Added a valid checksum to a problematic Liquibase changeset

### PR DESCRIPTION
**Pull request by Ceiu**
- Added a valid checksum to the consumer ID fact index changeset
  to fix an issue where Liquibase would detect an a mismatch when
  the changeset was actually valid

### CODE REVIEW

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
LGTM

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by barnabycourt** [comment]
performance ok

**Comment by barnabycourt** [comment]
retest this please

**Comment by barnabycourt** [comment]
retest this please

**Comment by barnabycourt** [comment]
performance ok

**Pull request merged**
