### PR TITLE
Use MariaDB JDBC connector. [ENT-986]

### PR DESCRIPTION
**Pull request by awood**
This commit leaves Liquibase still using the MySQL JDBC connector because the `mariadb-java-client` RPM isn't packaged in EPEL.  We can still use the JAR file in the deployed WAR though.

### CODE REVIEW

**Comment by Ceiu** [comment]
ack

Both failing tests here are due to issues in the automated testing environment. Manually executing either test passes as normal

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Lorquas** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
ack
Both connectors work fine when installed and "enabled" in bash_functions.

**Pull request merged**
