### PR TITLE
1330263: Subject Alternative Name not respected

### PR DESCRIPTION
**Pull request by nguyenfilip**
Since qpid-client version 0.32 the qpid-client respects extension X509v3
Subject Alternative Name

### CODE REVIEW

**Comment by nguyenfilip** [comment]
To test this, it is necessary to create a qpid server certificate with alternative name. I did this by modifying /etc/pki/tls/openssl.cnf: 

```
[ v3_ca ]
subjectAltName=DNS.1:10.40.5.138
```

And generating the keys using gutterball configure-qpid.sh. You can then check the generated qpid_qa.crt: 

```
openssl x509 -noout -in qpid_ca.crt -text
```

Then I reconfigured candlepin to use alternative name to connect instead  of  IP:

```
candlepin.amqp.enable = true
candlepin.amqp.connect=tcp://10.40.5.138:5671?ssl='true'&ssl_cert_alias='candlepin'
```

**Comment by vritant** [comment]
Note for the reviewer: Please ignore the PR check failures, the docker images are broken for older branches right now because we updated the gemlock file in master recently.

**Comment by barnabycourt** [comment]
@nguyenfilip Did you validate this with 'localhost' per the downstream bug?

**Comment by nguyenfilip** [comment]
@barnabycourt Originally I did the other way around (not using localhost as alternative name). Now I have just tested it as close to the downstream bug configuration as possible. See my approach below.

I reconfigured script 'configure-qpid.sh' to set CA_NAME of my Qpid CA certificate to my IP address:
```
CA_NAME="10.40.5.138"
```
I set the alternative name to 'localhost'. This is the output of "openssl x509 -noout -in qpid_ca.crt -text":
```
...
  Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Candlepin, CN=10.40.5.138
...
            X509v3 Subject Alternative Name: 
                DNS:localhost
...
```

I configured Candlepin to connect to localhost
```
candlepin.amqp.connect=tcp://localhost:5671?ssl='true'&ssl_cert_alias='candlepin'
```

Now when I use Qpid client version 0.30 I get several of the following warnings in Candlepin:
```
 WARN  org.apache.qpid.transport.network.security.ssl.SSLUtil - Exception received while trying to verify hostname
```

Followed by this exception:
```
javax.jms.JMSException: Error creating connection: SSL hostname verification failed. Expected : localhost Found in cert : 10.40.5.138
...
Caused by: org.apache.qpid.transport.ConnectionException: SSL hostname verification failed. Expected : localhost Found in cert : 10.40.5.138
```

Which is the reproducer of the bug. 

Now if I just bump up the version of Qpid client in buildfile to 0.32 and redeploy Candlepin, the logs are clear of any errors and Consumer spec tests run successfully (those publish into Qpid queues). See the following qpid status outputs, before and after:

Before running the spec tests:
```  
event               topic    Y       0   558      0     558     1.55m      0     1.55m
```

After running the spec tests:
```
event               topic    Y       0  1.31k     0    1.31k    2.80m      0     2.80m
```

Which proves the connection works to the broker works.

**Comment by Ceiu** [comment]
ACK

**Pull request merged**
