### PR TITLE
Update to Checkstyle 6.9

### PR DESCRIPTION
**Pull request by awood**
Users may need to start Eclipse with the `-clean` option if the were
using an old version of the Eclipse Checkstyle plugin.

Testing:

1. Run `buildr checkstyle`.  You should see some output about what is being checked but not see any errors.

2. Run `buildr eclipse`.

3. If you do not have the Eclipse Checkstyle plugin installed, it can be installed from `Help -> Eclipse Marketplace...` and then search for "checkstyle".

4. Go to `Project -> Clean...` and clean all your Candlepin projects.

5. If you see any errors complaining about classes that can't be found, close Eclipse, then run `eclipse -clean`

6. Go to a random file and type something like `if(true) { System.out.printline("hello");}`

7. A checkstyle warning should pop up immediately complaining about missing space between the if keyword and the left parenthesis.

### CODE REVIEW

**Comment by vritant** [comment]
NACK

[vrjain@localhost:{awood/update-checkstyle}:/NotBackedUp/code/candlepin/apicrawl]$ buildr checkstyle
(in /NotBackedUp/code/candlepin, development)
Running Checkstyle on candlepin:apicrawl
Checking /NotBackedUp/code/candlepin/apicrawl/^src/main/java/
[checkstyle] Running Checkstyle 6.9 on 6 files
E, [2015-09-18T18:10:50.810181 #24661] ERROR -- : Error instantiating 'checkstyle' task: Unable to persist cache file
Buildr aborted!
RuntimeError : java.lang.IllegalStateException: Unable to persist cache file

@awood  could you try buildr clean and then buildr checkstyle again and see if you get the same error please? @alikins  and I both reproduced this issue.

**Comment by awood** [comment]
@vritant Good catch.  Looks like if the `target` directory is missing due to a clean, it breaks.  Will fix.

**Comment by awood** [comment]
@vritant Should be good now.

**Comment by awood** [comment]
jenkins bot, retest this please.

**Comment by vritant** [comment]
@awood my eclipse showed a few more warnings, but the buildr tasks works now, so this better than what was before anyways. merging.

**Pull request merged**
