### PR TITLE
Automatic suspend mode transitions

### PR DESCRIPTION
**Pull request by nguyenfilip**
Candlepin will now automatically transition to/from Suspend Mode. This is
achieved by class SuspendModeTransitioner that technically uses
ScheduledExecutorService thead pool (single threaded). The transitioner
periodically runs checks for Qpid connectivity but also exposes public method
that can be used to attempt transition. The transition ends up being a no-op if
no transition is needed or ends up transitioning Candlepin from/to suspend mode.

### CODE REVIEW

**Comment by nguyenfilip** [comment]
@mstead this is the crucial PR for fail-fast that glues everything together.

**Comment by nguyenfilip** [comment]
@barnabycourt adding exponential back-off mechanism. It has configurable parameters:
```
QPID_MODE_TANSITIONER_DELAY_GROWTH = 2
QPID_MODE_TRANSITIONER_INITIAL_DELAY = 10
QPID_MODE_TRANSITIONER_MAX_DELAY = 1200
```

The delay is calculated using formula INITIAL_DELAY * (DELAY_GROWTH ^ FAILED_ATTEMPTS) . The MAX_DELAY gives ability to put upper limit to the resulting delay (-1 means unbounded). 

Its possible to also set the GROWTH to 1 which effectively disables "exponential back-off" and the delay becomes fixed INITIAL_DELAY

**Comment by nguyenfilip** [comment]
@barnabycourt the above default values are in seconds

**Comment by nguyenfilip** [comment]
retest this please

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
@nguyenfilip Please rebase.

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by mstead** [comment]
> @barnabycourt adding exponential back-off mechanism. It has configurable parameters:
> 
> QPID_MODE_TANSITIONER_DELAY_GROWTH = 2
> QPID_MODE_TRANSITIONER_INITIAL_DELAY = 10
> QPID_MODE_TRANSITIONER_MAX_DELAY = 1200
> 
> The delay is calculated using formula INITIAL_DELAY * (DELAY_GROWTH ^ FAILED_ATTEMPTS) . The MAX_DELAY gives ability to put upper limit to the resulting delay (-1 means unbounded).
> 
> Its possible to also set the GROWTH to 1 which effectively disables "exponential back-off" and the delay becomes fixed INITIAL_DELAY

These comments should be added to CandlepinConfig.java so that they are visible "in code". Useful information.

**Comment by nguyenfilip** [comment]
@mstead added

**Comment by nguyenfilip** [comment]
retest this please

**Pull request merged**
