### PR TITLE
Fix translations - un-escaped single quotes

### PR DESCRIPTION
**Pull request by vritant**
Automatically fixed translations using buildr validate_translation:fix

### CODE REVIEW

**Comment by awood** [comment]
Cool.  But are these changes just going to get clobbered when we merge down from Zanata again?

**Comment by vritant** [comment]
@awood  updated the documentation to add the validation step everytime: candlepin/candlepinproject.org#81
also, @Ceiu and I are collaborating so that we can run buildr check_all with every PR, which should prevent this from happening again.

**Comment by vritant** [comment]
@awood does that unblock the merge?

**Comment by awood** [comment]
> @awood does that unblock the merge?

Yes!

**Pull request merged**
