### PR TITLE
[M] 1608427: API call to get list of consumer UUIDs entitled from a pool

### PR DESCRIPTION
**Pull request by awood**

### CODE REVIEW

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by wottop** [comment]
ack

**Pull request merged**
