### PR TITLE
1469577: purge orphan pools via liquibase

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by vritant** [comment]
@candlepin-pull-request-bot  test this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by kahowell** [comment]
performance ok

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
retest this please

**Comment by mstead** [comment]
retest this please

**Pull request merged**
