### PR TITLE
[3.1] 1935300: Added additional checks for regenerating SCA certificates (ENT-3521)

### PR DESCRIPTION
**Pull request by Ceiu**
- SCA certificates will now be regenerated on request if the org's
  content, products, or pools change after the last cert update

### CODE REVIEW

**Comment by Ceiu** [comment]
Note for reviewers:
The 3.1 hotfix branch has 6 unit test failures that are not the result of any changes made in this PR. These should be fixed ASAP, but are outside the scope of this PR.

**Comment by Ceiu** [comment]
Blocked by #2955

**Comment by Ceiu** [comment]
Looks like "needs rebase" was the answer here -- something snuck another "isContentAccessEnabled" in that wasn't visible in this PR.

Also, note for reviewers: this is not just a cherry-pick of the changes. 3.1 and 4.0 are entirely incompatible in a lot of ways, and most of this logic needed to be rewritten completely. Please give this more attention than a typical backport would get.

**Review by sonalidhome — APPROVED** [review]
ack.

**Pull request merged**
