### PR TITLE
Upgrade Quartz to latest 2.2.1 (from 2013).

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by wottop** [comment]
TestBot: retest this please

**Comment by wottop** [comment]
You added a not-null column and then didn't seed it. I started up with master then ran the deploy/update.

Updating Database
Liquibase update Failed: Migration failed for change set db/changelog/20150818110722-upgrade-to-quartz-2-dot-2.xml::20150818110722-1::dgoodwin:
     Reason: liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE public.qrtz_fired_triggers ADD sched_time BIGINT NOT NULL: ERROR: column "sched_time" contains null values

**Comment by dgoodwin** [comment]
My bad, I can't seem to trigger this with a straight master + testdata deploy, then deploy on branch without -g. I will add a default ASAP.

**Comment by dgoodwin** [comment]
This might be a little tough to reproduce, entries in that table are transient, only existing when a trigger is being fired, not sure if that means there are rows when a job is running, or just before it actually launches. 

Quratz wants this field to be a bigint, not a datetime or anything we can work with easily. Following this response for the off chance you can get data in this table when doing an upgrade.

http://stackoverflow.com/questions/28211747/upgrade-to-quartz-2-2-jdbc-jobstore-new-column-sched-time

To test I deployed master and added a row of junk with:

insert into qrtz_fired_triggers(entry_id, trigger_name, trigger_group, instance_name, fired_time, priority, state_ values('a', 'a', 'a', 'a', 4000, 4000, 'a');

Then deploy this branch without -g to upgrade the db and ensure it's ok. I did this for both postgres and mysql, we have no pre-existing oracle db's so did not test this and disabled the changeset for those db's.

**Comment by dgoodwin** [comment]
retest this please

**Comment by dgoodwin** [comment]
Lets try this.

**Comment by dgoodwin** [comment]
Retest this please.

**Comment by Ceiu** [comment]
ACK
No issues deploying after priming the DB.

**Pull request merged**
