### PR TITLE
Fix test data file name in import products script

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by Ceiu** [comment]
This still leaves us with the problem of needing to run the script from the bin directory. I'd prefer we changed it to absolute paths or something relative to the script:

```ruby
script_home = File.dirname(File.expand_path($0))

filenames=["#{script_home}/test_data.json"]
```

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by vritant** [comment]
@Ceiu :+1:  done

**Comment by vritant** [comment]
@candlepin-pull-request-bot test again please

**Comment by vritant** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
ACK

**Pull request merged**
