### PR TITLE
1285004: Adds remove_by_pool_id to manager_capabilities

### PR DESCRIPTION
**Pull request by cnsnyder**
This adds the 'remove_by_pool_id' to the managerCapabilities string. This PR is required for a complete solution to BZ 1285004

### CODE REVIEW

**Comment by dgoodwin** [comment]
Can one of the admins verify this patch?

**Comment by wottop** [comment]
needs rebase for unit test issues

**Comment by cnsnyder** [comment]
@wottop I have rebased from master

**Comment by Ceiu** [comment]
ACK

```
crog@cl-vm-1:~/devel/candlepin/server(master) $ curl -k "https://localhost:8443/candlepin/status"
{
  "result" : true,
  "version" : "2.0.10",
  "rulesVersion" : "5.19",
  "release" : "1",
  "standalone" : true,
  "timeUTC" : "2015-12-03T16:14:59-0500",
  "managerCapabilities" : [ "cores", "ram", "instance_multiplier", "derived_product", "cert_v3", "guest_limit", "vcpu", "hypervisors_async", "storage_band" ],
  "rulesSource" : "DEFAULT"
}

crog@cl-vm-1:~/devel/candlepin/server(csnyder/1285004_Add_remove_pools_to_capabilities) $ curl -k "https://localhost:8443/candlepin/status"
{
  "result" : true,
  "version" : "2.0.10",
  "rulesVersion" : "5.19",
  "release" : "1",
  "standalone" : true,
  "timeUTC" : "2015-12-03T21:26:22.318+0000",
  "managerCapabilities" : [ "cores", "ram", "instance_multiplier", "derived_product", "cert_v3", "guest_limit", "vcpu", "hypervisors_async", "storage_band", "remove_by_pool_id" ],
  "rulesSource" : "DEFAULT"
}
```

**Pull request merged**
