### PR TITLE
1399820: Load exported count lazily due to nested call from entitlements

### PR DESCRIPTION
**Pull request by barnabycourt**

### CODE REVIEW

**Comment by mstead** [comment]
@barnabycourt I believe the version is incorrect in the referenced bug.

**Comment by mstead** [comment]
I'll merge once that is addressed.

**Comment by vritant** [comment]
This bug had a follow up second fix. is that needed here too?
we use hibernate 5 in master, hence the question.

**Comment by vritant** [comment]
Nacking this fix on its own based on performance results. a performance test of just get consumers had a negligible improvement in results ( 14069 vs 14847 in master )

**Comment by barnabycourt** [comment]
@vritant How many entitlements or referenced pools were available in the account used for testing? A much better fix for this issue generally would be to stop dynamically calculating exported count & consumed count dynamically

**Comment by mstead** [comment]
We should port the 0.9.54 FieldHandler fix into master so that Lazy loading with '@Formula' is actually performed lazily.

**Pull request closed without merging**
