### PR TITLE
Add API to clear productfullcache

### PR DESCRIPTION
**Pull request by cnsnyder**
In theory one should be able to see this api work by a curl something like the following:
`curl -ik -u admin:admin --request DELETE "https://localhost:8443/candlepin/admin/cache/product"`

You should be able to see the cache be cleared in jconsole by enabling statistics for ehcache by following the instructions found here: http://www.candlepinproject.org/docs/candlepin/caching.html

### CODE REVIEW

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot retest this please

**Comment by cnsnyder** [comment]
test this please

**Comment by nguyenfilip** [comment]
@cnsnyder After style fixes and unit test fixes this should be good. Your code works, I have added a few more logging statements [1] that prove it. 

A disturbing thing (that is not going to hold up this PR) is that statistics doesn't work (I created [BZ1400636](https://bugzilla.redhat.com/show_bug.cgi?id=1400636) to track that)


[1]
```
        log.debug("Removing all from the product cache");
        net.sf.ehcache.Cache unwrapped =
            (net.sf.ehcache.Cache) candlepinCache
            .getProductCache().unwrap(net.sf.ehcache.Cache.class);
        long size = unwrapped.getStatistics().getLocalHeapSize();
        log.debug("Current cache local heap size: {}", size);
        Cache<String, Product> productCache = candlepinCache.getProductCache();
        productCache.removeAll();
        size = unwrapped.getStatistics().getLocalHeapSize();
        log.debug("Current cache local heap size: {}", size);
```
```
[fnguyen@localhost candlepin]$ curl -ik -u admin:admin --request DELETE "https://localhost:8443/candlepin/admin/cache/product"
HTTP/1.1 204 No Content
Server: Apache-Coyote/1.1
x-candlepin-request-uuid: e8b9bcbd-583c-4801-8bf0-b7459c8ecc98
X-Version: 2.0.20-1
Date: Thu, 01 Dec 2016 16:46:22 GMT
```

```
2016-12-01 17:46:22,916 [thread=http-nio-8443-exec-1] [req=e8b9bcbd-583c-4801-8bf0-b7459c8ecc98, org=] DEBUG org.candlepin.resource.AdminResource - Removing all from the product cache
2016-12-01 17:46:22,916 [thread=http-nio-8443-exec-1] [req=e8b9bcbd-583c-4801-8bf0-b7459c8ecc98, org=] DEBUG org.candlepin.resource.AdminResource - Current cache local heap size: 6
2016-12-01 17:46:22,923 [thread=http-nio-8443-exec-1] [req=e8b9bcbd-583c-4801-8bf0-b7459c8ecc98, org=] DEBUG org.candlepin.resource.AdminResource - Current cache local heap size: 0
```

**Comment by cnsnyder** [comment]
test this please

**Comment by nguyenfilip** [comment]
ack

**Pull request merged**
