### PR TITLE
Swagger integration for development purposes

### PR DESCRIPTION
**Pull request by nguyenfilip**
This is first PR against the development branch. It introduces swagger.json integration for OwnerResource and StatusResource. After deploying Candlepin, the swagger.json is available at: http://localhost:8080/candlepin/swagger.json and the Swagger UI documentation is available at http://localhost:8080/candlepin/docs

### CODE REVIEW

**Comment by nguyenfilip** [comment]
Adding in-progress as there are still test failures that I need to deal with

**Comment by nguyenfilip** [comment]
rebuild this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by nguyenfilip** [comment]
This PR is being replaced by 1195. In 1195, I rebased the development branch as well as the PR against the master. Reason: so that specs pass.

**Pull request closed without merging**
