### PR TITLE
Delete missing products from activation keys while upgrading.

### PR DESCRIPTION
**Pull request by awood**
If a user has an activation key referencing a product that no longer
exists, we now just delete that reference rather that halting the entire
migration.

### CODE REVIEW

**Comment by Ceiu** [comment]
Activation key:
```
(16:25:22) crog@cl-vm-1:~/devel/candlepin-origin/server(master) $ ./client/ruby/cpc list_activation_keys admin
[{"id"=>"ff8080815f26d9fb015f26db8de02302",
  "name"=>"testkey",
  "description"=>nil,
  "owner"=>
   {"id"=>"ff8080815f26d9fb015f26da449d0002",
    "key"=>"admin",
    "displayName"=>"Admin Owner",
    "href"=>"/owners/admin"},
  "pools"=>[],
  "productIds"=>[{"id"=>"very_random_key", "productId"=>"bad-prod-ref"}],
  "contentOverrides"=>[],
  "releaseVer"=>{"releaseVer"=>nil},
  "serviceLevel"=>nil,
  "autoAttach"=>nil,
  "created"=>"2017-10-16T20:24:03.808+0000",
  "updated"=>"2017-10-16T20:24:03.808+0000"},
...


Master:
```
During migration:
SEVERE 10/16/17 4:28 PM: liquibase: db/changelog/changelog-update.xml: db/changelog/20150210094558-perorgproducts-phase-1.xml::20150210094558-35::crog:   Activation Key "ff8080815f26d9fb015f26db8de02302" references an unresolvable product: bad-prod-ref
```

This branch:
```
INFO 10/16/17 4:34 PM: liquibase: db/changelog/changelog-update.xml: db/changelog/20150210094558-perorgproducts-phase-1.xml::20150210094558-35::crog: Fixed 1 activation keys referencing missing products
...
INFO 10/16/17 4:34 PM: liquibase: Successfully released change log lock
Liquibase Update Successful
```

**Comment by Ceiu** [comment]
Code looks good, and manual test passed as expected. The one thing I worry about is that the removal of the value prevents any kind of fix post-migration if there aren't any other record or memory of what the referenced product was supposed to be, or even that it was supposed to exist.

This is still probably the better of the two options, as if the product didn't exist to begin with, the activation key already wasn't doing anything with that data.

**Comment by Ceiu** [comment]
Also, we'll need a forward port to master once this is merged.

**Comment by awood** [comment]
Github was being weird and not showing the force push.  Reopened as #1755

**Pull request closed without merging**
