### PR TITLE
Data eager loading in ConsumerResource.bin

### PR DESCRIPTION
**Pull request by nguyenfilip**
Improving performance of bind() operation by introducing Hibernate batching and adding a new method to Consumer currator that retrieves information related to the Consumer more eagerly in lower amount of queries

### CODE REVIEW

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
@Ceiu I have just rebased this on master (which should have fixed unit tests now)

**Comment by Ceiu** [comment]
I'm not seeing any difference in the number of queries issued with this branch

```
(10:45:44) crog@crog-ws-1:~/devel/candlepin/server(master) $ sudo truncate --size=0 /var/log/candlepin/candlepin.log 
(10:47:47) crog@crog-vm-1:~ $ sudo subscription-manager attach --pool=8a8d01cb516dab2401516dab7ccd0553
1 local certificate has been deleted.
Successfully attached a subscription for: Awesome OS Workstation Basic
(10:47:44) crog@crog-ws-1:~/devel/candlepin/server(master) $ grep -Pc 'DEBUG org.hibernate.SQL - (?!(select .* from cp_job)|(update cp_job))' /var/log/candlepin/candlepin.log 
298


(10:49:48) crog@crog-ws-1:~/devel/candlepin/server(nguyenfilip/n1-bind-by-pool) $ sudo truncate --size=0 /var/log/candlepin/candlepin.log 
(10:50:04) crog@crog-vm-1:~ $ sudo subscription-manager attach --pool=8a8d01cb516daee401516daf3b60055d
1 local certificate has been deleted.
Successfully attached a subscription for: Awesome OS Workstation Basic
(10:50:11) crog@crog-ws-1:~/devel/candlepin/server(nguyenfilip/n1-bind-by-pool) $ grep -Pc 'DEBUG org.hibernate.SQL - (?!(select .* from cp_job)|(update cp_job))' /var/log/candlepin/candlepin.log 
298
```

**Comment by Ceiu** [comment]
Scratch that. While attacking multiple pools, there's a very clear difference -- almost a 50% gain with the test data.

ACK
```
(11:02:49) crog@crog-ws-1:~/devel/candlepin/server(master) $ sudo truncate --size=0 /var/log/candlepin/candlepin.log 
(11:04:31) crog@crog-vm-1:~ $ sudo subscription-manager attach --file pools.txt                 
102 local certificates have been deleted.
Successfully attached a subscription for: RAM Limiting Package (4GB stackable)
Successfully attached a subscription for: Development SKU Product
Successfully attached a subscription for: Awesome OS for x86_64/i686/ia64/ppc/ppc64/s390x/s390
Successfully attached a subscription for: Awesome OS Docker
Successfully attached a subscription for: Awesome OS OSTree
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB)
Successfully attached a subscription for: Shared File System
Successfully attached a subscription for: Awesome OS Modifier
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Admin OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Management Add-On
Successfully attached a subscription for: Awesome OS physical with unlimited guests
Successfully attached a subscription for: Multi-Attribute Stackable (2 sockets)
Successfully attached a subscription for: RAM Limiting Package (8GB)
Successfully attached a subscription for: Stackable with Awesome OS for x86_64
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB, 2 Cores)
Successfully attached a subscription for: Multi-Attribute (multi-entitlement only) (8 cores, 4GB)
Successfully attached a subscription for: RAM Limiting Package (4GB stackable)
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Multi-Attribute (multi-entitlement only) (8 cores, 4GB)
Successfully attached a subscription for: Admin OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Awesome OS for All Arch (all per arch content)
Successfully attached a subscription for: Multi-Attribute (non-stackable) (6 cores, 8GB)
Successfully attached a subscription for: Multi-Attribute Stackable (2 sockets)
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Cores Package (26 cores)
Successfully attached a subscription for: Awesome OS for All Arch (excpt for x86_64 content)
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB, 2 Cores)
Successfully attached a subscription for: Awesome OS for All Arch (all per arch content)
Successfully attached a subscription for: Awesome OS Server Basic
Successfully attached a subscription for: Multi-Attribute (non-stackable) (6 cores, 8GB)
Successfully attached a subscription for: Awesome OS Virtual Datacenter
Successfully attached a subscription for: Awesome OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Awesome OS physical with unlimited guests
Successfully attached a subscription for: Stackable Cores Package (8 cores)
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Stackable Cores Package (8 cores)
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Multi-Attribute Stackable (4 cores)
Successfully attached a subscription for: Awesome OS Server Bundled
Successfully attached a subscription for: Awesome OS for All Arch (excpt for x86_64 content)
Successfully attached a subscription for: RAM Limiting Package (2GB stackable)
Successfully attached a subscription for: Awesome OS Virtual Datacenter
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Development SKU Product
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: RAM/Cores Package (8GB, 4 cores)
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Awesome OS Server Basic (data center)
Successfully attached a subscription for: Awesome OS Server Basic (multi-entitlement)
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Awesome OS OSTree
Successfully attached a subscription for: Awesome OS Server Basic (multi-entitlement)
Successfully attached a subscription for: RAM Limiting Package (8GB)
Successfully attached a subscription for: Storage Limited (256 TB)
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Cores Package (26 cores)
Successfully attached a subscription for: Shared File System
Successfully attached a subscription for: Awesome OS for x86_64
Successfully attached a subscription for: RAM/Cores Package (8GB, 4 cores)
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB)
Successfully attached a subscription for: Awesome OS Server Basic (data center)
Successfully attached a subscription for: Multi-Attribute (non-stackable) (24 cores, 6 sockets, 8GB RAM)
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: Awesome OS for All Arch (x86content)
Successfully attached a subscription for: Stackable with Awesome OS for x86_64
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Multi-Attribute Stackable (16 cores, 4 sockets, 8GB RAM)
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Awesome OS for x86_64
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: RAM Limiting Package (2GB stackable)
Successfully attached a subscription for: Awesome OS Docker
Successfully attached a subscription for: Awesome OS for All Arch (just x86_64 content)
Successfully attached a subscription for: Multi-Attribute (non-stackable) (24 cores, 6 sockets, 8GB RAM)
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Multi-Attribute Stackable (16 cores, 4 sockets, 8GB RAM)
Successfully attached a subscription for: Awesome OS Server Basic
Successfully attached a subscription for: Awesome OS Workstation Basic
Successfully attached a subscription for: Management Add-On
Successfully attached a subscription for: Awesome OS Server Bundled
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Storage Limited (256 TB)
Successfully attached a subscription for: Multi-Attribute Stackable (4 cores)
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Awesome OS for All Arch (just x86_64 content)
Successfully attached a subscription for: Awesome OS for All Arch (x86content)
Successfully attached a subscription for: Awesome OS Modifier
Successfully attached a subscription for: Awesome OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Awesome OS Workstation Basic
Successfully attached a subscription for: Awesome OS for x86_64/i686/ia64/ppc/ppc64/s390x/s390
(11:04:37) crog@crog-ws-1:~/devel/candlepin/server(master) $ grep -Pc 'DEBUG org.hibernate.SQL - (?!(select .* from cp_job)|(update cp_job))' /var/log/candlepin/candlepin.log 
49652
```
===
```
(10:57:27) crog@crog-ws-1:~/devel/candlepin/server(nguyenfilip/n1-bind-by-pool) $ sudo truncate --size=0 /var/log/candlepin/candlepin.log 
(10:58:13) crog@crog-vm-1:~ $ sudo subscription-manager attach --file pools.txt
1 local certificate has been deleted.
Successfully attached a subscription for: Awesome OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Awesome OS OSTree
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Awesome OS Modifier
Successfully attached a subscription for: Awesome OS OSTree
Successfully attached a subscription for: Storage Limited (256 TB)
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Awesome OS for All Arch (x86content)
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Management Add-On
Successfully attached a subscription for: Multi-Attribute Stackable (4 cores)
Successfully attached a subscription for: Multi-Attribute Stackable (4 cores)
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB)
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Multi-Attribute Stackable (16 cores, 4 sockets, 8GB RAM)
Successfully attached a subscription for: Multi-Attribute (multi-entitlement only) (8 cores, 4GB)
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Awesome OS Workstation Basic
Successfully attached a subscription for: Stackable with Awesome OS for x86_64
Successfully attached a subscription for: Development SKU Product
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Awesome OS for All Arch (x86content)
Successfully attached a subscription for: Awesome OS Server Basic (multi-entitlement)
Successfully attached a subscription for: Awesome OS for All Arch (excpt for x86_64 content)
Successfully attached a subscription for: Management Add-On
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: Awesome OS for All Arch (just x86_64 content)
Successfully attached a subscription for: Awesome OS Virtual Datacenter
Successfully attached a subscription for: Awesome OS Virtual Datacenter
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Awesome OS for x86_64
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: Multi-Attribute Stackable (2 sockets)
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Awesome OS Workstation Basic
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB, 2 Cores)
Successfully attached a subscription for: Awesome OS Instance Based one socket
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: RAM Limiting Package (8GB)
Successfully attached a subscription for: Awesome OS Server Bundled
Successfully attached a subscription for: Awesome OS for x86_64/i686/ia64/ppc/ppc64/s390x/s390
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Multi-Attribute (non-stackable) (24 cores, 6 sockets, 8GB RAM)
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB)
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Cores Package (26 cores)
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Awesome OS for All Arch (just x86_64 content)
Successfully attached a subscription for: Awesome OS physical with unlimited guests
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: Multi-Attribute (multi-entitlement only) (8 cores, 4GB)
Successfully attached a subscription for: Awesome OS for x86_64/i686/ia64/ppc/ppc64/s390x/s390
Successfully attached a subscription for: Awesome OS Server Bundled
Successfully attached a subscription for: Awesome OS Server Basic
Successfully attached a subscription for: Admin OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Awesome OS for All Arch (all per arch content)
Successfully attached a subscription for: Awesome OS Server Basic
Successfully attached a subscription for: Awesome OS Server Basic (data center)
Successfully attached a subscription for: Awesome OS Server Basic (multi-entitlement)
Successfully attached a subscription for: Multi-Attribute Stackable (2 GB, 2 Cores)
Successfully attached a subscription for: RAM Limiting Package (4GB stackable)
Successfully attached a subscription for: RAM/Cores Package (8GB, 4 cores)
Successfully attached a subscription for: Stackable with Awesome OS for x86_64
Successfully attached a subscription for: Awesome OS Docker
Successfully attached a subscription for: Multi-Attribute (non-stackable) (6 cores, 8GB)
Successfully attached a subscription for: RAM Limiting Package (2GB stackable)
Successfully attached a subscription for: Awesome OS Instance Based (Standard Support)
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Awesome OS Server Basic (data center)
Successfully attached a subscription for: Multi-Attribute Stackable (2 sockets)
Successfully attached a subscription for: Multi-Attribute (non-stackable) (6 cores, 8GB)
Successfully attached a subscription for: Multi-Attribute Stackable (16 cores, 4 sockets, 8GB RAM)
Successfully attached a subscription for: Stackable Cores Package (8 cores)
Successfully attached a subscription for: RAM Limiting Package (4GB stackable)
Successfully attached a subscription for: RAM/Cores Package (8GB, 4 cores)
Successfully attached a subscription for: Awesome OS physical with unlimited guests
Successfully attached a subscription for: Awesome OS Modifier
Successfully attached a subscription for: Awesome OS for x86_64
Successfully attached a subscription for: Awesome OS Stackable guest limit 4
Successfully attached a subscription for: Shared File System
Successfully attached a subscription for: Awesome OS with up to 4 virtual guests
Successfully attached a subscription for: Awesome OS Docker
Successfully attached a subscription for: Admin OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Awesome OS for All Arch (excpt for x86_64 content)
Successfully attached a subscription for: RAM Limiting Package (8GB)
Successfully attached a subscription for: Admin OS Instance Based one socket
Successfully attached a subscription for: Multi-Attribute (non-stackable) (24 cores, 6 sockets, 8GB RAM)
Successfully attached a subscription for: Awesome OS Super Hypervisor
Successfully attached a subscription for: RAM Limiting Package (2GB stackable)
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Shared File System
Successfully attached a subscription for: Awesome OS with unlimited virtual guests
Successfully attached a subscription for: Development SKU Product
Successfully attached a subscription for: Awesome OS Server Bundled (2 Sockets, Standard Support)
Successfully attached a subscription for: Cores Package (26 cores)
Successfully attached a subscription for: Awesome OS for All Arch (all per arch content)
Successfully attached a subscription for: Stackable Cores Package (8 cores)
Successfully attached a subscription for: Storage Limited (256 TB)
(10:58:27) crog@crog-ws-1:~/devel/candlepin/server(nguyenfilip/n1-bind-by-pool) $ grep -Pc 'DEBUG org.hibernate.SQL - (?!(select .* from cp_job)|(update cp_job))' /var/log/candlepin/candlepin.log 
24060
```

**Pull request merged**
