### PR TITLE
1460731: Handle job creation failure graciously ( master )

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by vritant** [comment]
[1460731, 1459985 Refresh Pools Jobs stuck in created state](https://trello.com/c/VCldq8YG/449-1460731-1459985-refresh-pools-jobs-stuck-in-created-state)

**Comment by kahowell** [comment]
retest this please

**Comment by mstead** [comment]
retest this please

**Comment by kahowell** [comment]
Only jenkins failure was the performance tests, so that can be ignored.

**Pull request merged**
