### PR TITLE
1503179: Delete missing products from activation keys while upgrading.

### PR DESCRIPTION
**Pull request by awood**
If a user has an activation key referencing a product that no longer
exists, we now just delete that reference rather that halting the entire
migration.

### CODE REVIEW

**Comment by wottop** [comment]
retest this please

**Comment by wottop** [comment]
The failure is legit. When I ran owner_product_resource_spec locally, I see the same error.

**Comment by awood** [comment]
@candlepin-pull-request-bot retest this please

**Comment by awood** [comment]
> The failure is legit. When I ran owner_product_resource_spec locally, I see the same error.

I have no idea how this PR could be related to that failure.  This code is only run during a liquibase migration and, as far as I know, no migrations are performed during the spec test runs.  Also the CI environment is passing it now.

My theory is that the test itself fails intermittently and we would see the same behavior on the base branch.

**Comment by wottop** [comment]
the test passes. ack.

**Pull request merged**
