### PR TITLE
ENT-1877: port JobResource to spec-first

### PR DESCRIPTION
**Pull request by abhiskum**
- Remove exiting SchedulerStatusDTO and generated using spec-first
 - Added API specification in candlepin-api-spec
 - Updated existing JUnit

### CODE REVIEW

**Comment by abhiskum** [comment]
https://projects.engineering.redhat.com/browse/ENT-2177.

**Comment by wottop** [comment]
Please rebase. Is this relying on something else to complete?

**Comment by nikosmoum** [comment]
@wottop yes, this is dependent on https://github.com/candlepin/candlepin/pull/2663 being merged first

**Comment by wottop** [comment]
#2663 is complete, please proceed with the review.

**Pull request merged**
