### PR TITLE
Provide explicit serialVersionUIDs.

### PR DESCRIPTION
**Pull request by awood**
@crog This PR can be tacked onto #1152

### CODE REVIEW

**Comment by mstead** [comment]
@awood it might be worth adding a little but of context to the commit message as to why this was needed.

**Comment by Ceiu** [comment]
Were these UIDs randomly generated, or are they the values currently being used by Java (disregarding the compiler implementation details mentioned on the other PR)?

**Comment by awood** [comment]
> Were these UIDs randomly generated, or are they the values currently being used by Java (disregarding the compiler implementation details mentioned on the other PR)?

They're compiler generated ones courtesy of Eclipse.

**Comment by mstead** [comment]
What was the reason this was needed again?

**Comment by Ceiu** [comment]
@mstead We have a case going from 0.9x to 2 where a task class changes slightly (just enough for the serialVersionUID to change), but the functionality doesn't. But due to the way serialization works, Java throws an exception all the same because the version UIDs don't match.

**Comment by mstead** [comment]
Ah right. I recall that now. Thanks.

**Pull request merged**
