### PR TITLE
[M] Added a valid checksum to a problematic Liquibase changeset

### PR DESCRIPTION
**Pull request by Ceiu**
- Added a valid checksum to the consumer ID fact index changeset
  to fix an issue where Liquibase would detect an a mismatch when
  the changeset was actually valid

### CODE REVIEW

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
The unit test failures in this branch are addressed by #1722. This branch should be rebased against master once #1722 is merged.

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by mstead** [comment]
performance ok

**Comment by awood** [comment]
Any idea why Liquibase is having a problem with this particular changeset?  It's two years old at least so has something recently gone awry?

**Comment by Ceiu** [comment]
@awood I'm guessing the original version went out to a Sat build, but they didn't see the update that was made shortly afterward. In general, it's fine, but we're seeing collisions when we get database dumps from some customers and Sat deployments.

**Comment by awood** [comment]
Okay.  This looks fine to me as well.  Ready for merge, IMO, once Jenkins gets back in line.

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by Ceiu** [comment]
@candlepin-pull-request-bot retest this please

**Comment by barnabycourt** [comment]
retest this please

**Pull request merged**
