### PR TITLE
[0.9.54] 1519900: Added a per-org products migration validation Liquibase task

### PR DESCRIPTION
**Pull request by Ceiu**
- Added a new set of liquibase tasks which perform database
  validation rather than modification. These are part of the new
  changelog-validate.xml file and are not included in any of the
  existing changelog collections.
- Updated cpdb to have a --validate option, which runs the new
  validation set of Liquibase tasks
- Added --verbose to cpdb, which sets the logging level in
  Liquibase to "debug"
- Added the PerOrgProductsMigrationValidationTask and Liquibase
  wrapper
- Minor whitespace and spelling corrections throughout cpdb and
  cpsetup

### CODE REVIEW

**Comment by Ceiu** [comment]
This is a backport of the updated cpdb validation and logging functionality from 2.0, including the validation task for the per-org products migration.

**Comment by Ceiu** [comment]
[Back port cpdb --validate changes to 0.9.54](https://trello.com/c/kdp6wF29/690-back-port-cpdb-validate-changes-to-0954)

**Comment by mstead** [comment]
@Ceiu Please make sure that this PR addresses the concerns in:
https://bugzilla.redhat.com/show_bug.cgi?id=1519904

Leave them a comment as to what they can expect and some details around what the script will output if the migration has already been attempted and what they should do to find the validation errors in this case.

**Comment by mstead** [comment]
@Ceiu adding this comment to track what we talked about.

'cpdb --validate' will not run the changeset once it has run successfully. We should make the changeset run each time UNLESS we have already migrated.

**Comment by Ceiu** [comment]
Added "runAlways" to the changeset, as the preconditions are what we care about here.

**Pull request merged**
