### PR TITLE
Add index ( target id, type ) on cp_job - 2.1

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by vritant** [comment]
only the tests with postgres database fail with this error:

> 14:47:45 Liquibase update Failed: Migration failed for change set db/changelog/20171017062314-add-target-index-on-job-table.xml::20171017062314-1::vrjain:
14:47:45      Reason: 
14:47:45           db/changelog/changelog-create.xml : Index Exists Precondition: idx_job_targetIDType : ERROR: column am.amcanorder does not exist
14:47:45   Position: 407
14:47:45 


basically, we recently upgraded our docker images to have postgresql-server-9.6 , which has this issue.
I will dig into this further next week.

**Comment by barnabycourt** [comment]
@vritant RHEL 7.4 is running Postgres 9.2.23. Do we care about a newer version at this point?

**Comment by vritant** [comment]
@mstead apologies, I assumed the card had the appropriate name, so I went with that. checked with tdarby, the name matches with this PR.

**Comment by barnabycourt** [comment]
[Perf Issue: Create index on cp_job table for 2.x](https://trello.com/c/yAHScVv5/595-perf-issue-create-index-on-cpjob-table-for-2x)

**Comment by barnabycourt** [comment]
[Perf Issue: Create index on cp_job table for 2.x](https://trello.com/c/yAHScVv5/595-perf-issue-create-index-on-cpjob-table-for-2x)

**Pull request merged**
